"use client";

import { useMemo, useState } from "react";

type LocaleCode = "en" | "pl" | "ru" | "uk" | "de" | "es" | "cs";
type Profile = { accumulated_unit_code:string; calculation_mode:string; source_parameter_code:string; baseline_value:number; target_value:number|null; critical_value:number|null; desired_direction:string; refresh_period_days:number|null; inactivity_delta:number; trend_window_days:number };
type State = { currentValue:number; accumulatedUnitCode:string; trendDelta:number; trendDirection:string; ratePerDay:number|null; targetValue:number|null; criticalValue:number|null; daysToTarget:number|null; daysToCritical:number|null; missedRefreshPeriods:number; factContributions:number };
type Rule = { id:string; source_value_object_id:string; source_parameter_code:string; coefficient:number; status:string; sourceValueObjectTitle:string };
type Bundle = { ok?:boolean; error?:string; profile?:Profile|null; state?:State|null; rules?:Rule[] };
type SelectorItem = { id:string; title:string; level?:string; pathText?:string };
type Form = { unit:string; mode:string; parameter:string; baseline:string; target:string; critical:string; direction:string; refreshDays:string; inactivityDelta:string; trendDays:string };

const TEXT: Record<LocaleCode, {title:string;intro:string;open:string;close:string;save:string;current:string;trend:string;rate:string;target:string;critical:string;daysTarget:string;daysCritical:string;missed:string;facts:string;unit:string;mode:string;parameter:string;baseline:string;targetValue:string;criticalValue:string;direction:string;refresh:string;inactivity:string;trendWindow:string;rules:string;ruleHelp:string;search:string;sourceParameter:string;coefficient:string;add:string;remove:string;empty:string;notConfigured:string}> = {
  en:{title:"Accumulated effect and trajectory",intro:"Calculated from filtered confirmed facts. Raw facts are never rewritten. The value may be absolute or an abstract scale where sign, trend and time to zero/target matter most.",open:"Configure analytics",close:"Close",save:"Save profile",current:"Accumulated effect",trend:"Trend",rate:"Rate / day",target:"Target",critical:"Critical boundary",daysTarget:"Days to target",daysCritical:"Days to critical",missed:"Missed refresh periods",facts:"Fact contributions",unit:"Unit",mode:"Calculation mode",parameter:"Fact parameter",baseline:"Baseline",targetValue:"Target value",criticalValue:"Critical value",direction:"Desired direction",refresh:"Refresh period, days",inactivity:"Change per missed period",trendWindow:"Trend window, days",rules:"Analytics effect coefficients",ruleHelp:"These coefficients affect only analytics calculations and never persisted facts.",search:"Find source leaf",sourceParameter:"Source fact parameter",coefficient:"Effect coefficient",add:"Add coefficient",remove:"Remove",empty:"No active coefficients.",notConfigured:"Analytics profile is not configured yet."},
  pl:{title:"Efekt skumulowany i trajektoria",intro:"Obliczane z przefiltrowanych potwierdzonych faktów. Surowe fakty nigdy nie są przepisywane. Wartość może być bezwzględna albo umowna, gdzie najważniejszy jest znak, trend i czas do zera/celu.",open:"Skonfiguruj analitykę",close:"Zamknij",save:"Zapisz profil",current:"Efekt skumulowany",trend:"Trend",rate:"Tempo / dzień",target:"Cel",critical:"Granica krytyczna",daysTarget:"Dni do celu",daysCritical:"Dni do granicy",missed:"Pominięte okresy",facts:"Wkłady faktów",unit:"Jednostka",mode:"Sposób obliczania",parameter:"Parametr faktu",baseline:"Stan początkowy",targetValue:"Wartość docelowa",criticalValue:"Wartość krytyczna",direction:"Pożądany kierunek",refresh:"Okres odświeżenia, dni",inactivity:"Zmiana za pominięty okres",trendWindow:"Okno trendu, dni",rules:"Współczynniki efektu",ruleHelp:"Współczynniki wpływają tylko na analitykę, nigdy na zapisane fakty.",search:"Znajdź liść źródłowy",sourceParameter:"Parametr źródłowy",coefficient:"Współczynnik",add:"Dodaj współczynnik",remove:"Usuń",empty:"Brak aktywnych współczynników.",notConfigured:"Profil analityczny nie jest jeszcze skonfigurowany."},
  ru:{title:"Накопленный эффект и траектория",intro:"Рассчитывается из отфильтрованных подтвержденных фактов. Исходные факты никогда не переписываются. Значение может быть абсолютным либо условным, где важнее знак, тенденция и срок до нуля/цели.",open:"Настроить аналитику",close:"Закрыть",save:"Сохранить профиль",current:"Накопленный эффект",trend:"Тенденция",rate:"Скорость / день",target:"Цель",critical:"Критическая граница",daysTarget:"Дней до цели",daysCritical:"Дней до критической границы",missed:"Пропущено периодов обновления",facts:"Учтено вкладов фактов",unit:"Единица",mode:"Способ расчета",parameter:"Параметр факта",baseline:"Начальное значение",targetValue:"Целевое значение",criticalValue:"Критическое значение",direction:"Желательное направление",refresh:"Период обновления, дней",inactivity:"Изменение за пропущенный период",trendWindow:"Окно тенденции, дней",rules:"Коэффициенты аналитического эффекта",ruleHelp:"Коэффициенты влияют только на расчет аналитики и никогда не меняют записанные факты.",search:"Найти лист-источник",sourceParameter:"Параметр исходного факта",coefficient:"Коэффициент эффекта",add:"Добавить коэффициент",remove:"Удалить",empty:"Активных коэффициентов нет.",notConfigured:"Профиль аналитики пока не настроен."},
  uk:{title:"Накопичений ефект і траєкторія",intro:"Розраховується з відфільтрованих підтверджених фактів. Вихідні факти не переписуються.",open:"Налаштувати аналітику",close:"Закрити",save:"Зберегти профіль",current:"Накопичений ефект",trend:"Тенденція",rate:"Швидкість / день",target:"Ціль",critical:"Критична межа",daysTarget:"Днів до цілі",daysCritical:"Днів до межі",missed:"Пропущено періодів",facts:"Внески фактів",unit:"Одиниця",mode:"Спосіб розрахунку",parameter:"Параметр факту",baseline:"Початкове значення",targetValue:"Цільове значення",criticalValue:"Критичне значення",direction:"Бажаний напрям",refresh:"Період оновлення, днів",inactivity:"Зміна за пропущений період",trendWindow:"Вікно тенденції, днів",rules:"Коефіцієнти ефекту",ruleHelp:"Коефіцієнти змінюють лише аналітику, не факти.",search:"Знайти лист-джерело",sourceParameter:"Параметр джерела",coefficient:"Коефіцієнт",add:"Додати",remove:"Видалити",empty:"Активних коефіцієнтів немає.",notConfigured:"Профіль ще не налаштований."},
  de:{title:"Kumulierter Effekt und Verlauf",intro:"Berechnung aus gefilterten bestätigten Fakten. Rohfakten werden nie überschrieben.",open:"Analytik konfigurieren",close:"Schließen",save:"Profil speichern",current:"Kumulierter Effekt",trend:"Trend",rate:"Rate / Tag",target:"Ziel",critical:"Kritische Grenze",daysTarget:"Tage bis Ziel",daysCritical:"Tage bis Grenze",missed:"Verpasste Perioden",facts:"Faktbeiträge",unit:"Einheit",mode:"Berechnungsart",parameter:"Faktparameter",baseline:"Ausgangswert",targetValue:"Zielwert",criticalValue:"Kritischer Wert",direction:"Gewünschte Richtung",refresh:"Aktualisierung, Tage",inactivity:"Änderung je Ausfall",trendWindow:"Trendfenster, Tage",rules:"Effektkoeffizienten",ruleHelp:"Koeffizienten ändern nur die Analytik, nie Fakten.",search:"Quellblatt suchen",sourceParameter:"Quellparameter",coefficient:"Koeffizient",add:"Hinzufügen",remove:"Entfernen",empty:"Keine aktiven Koeffizienten.",notConfigured:"Noch kein Profil konfiguriert."},
  es:{title:"Efecto acumulado y trayectoria",intro:"Calculado a partir de hechos confirmados filtrados. Los hechos originales nunca se reescriben.",open:"Configurar analítica",close:"Cerrar",save:"Guardar perfil",current:"Efecto acumulado",trend:"Tendencia",rate:"Velocidad / día",target:"Objetivo",critical:"Límite crítico",daysTarget:"Días al objetivo",daysCritical:"Días al límite",missed:"Periodos omitidos",facts:"Contribuciones",unit:"Unidad",mode:"Modo de cálculo",parameter:"Parámetro del hecho",baseline:"Valor inicial",targetValue:"Valor objetivo",criticalValue:"Valor crítico",direction:"Dirección deseada",refresh:"Periodo de actualización, días",inactivity:"Cambio por periodo omitido",trendWindow:"Ventana de tendencia, días",rules:"Coeficientes de efecto",ruleHelp:"Los coeficientes solo cambian la analítica, nunca los hechos.",search:"Buscar hoja fuente",sourceParameter:"Parámetro fuente",coefficient:"Coeficiente",add:"Añadir",remove:"Eliminar",empty:"No hay coeficientes activos.",notConfigured:"Perfil no configurado."},
  cs:{title:"Nahromaděný efekt a trajektorie",intro:"Výpočet z filtrovaných potvrzených faktů. Původní fakta se nikdy nepřepisují.",open:"Nastavit analytiku",close:"Zavřít",save:"Uložit profil",current:"Nahromaděný efekt",trend:"Trend",rate:"Rychlost / den",target:"Cíl",critical:"Kritická hranice",daysTarget:"Dní do cíle",daysCritical:"Dní do hranice",missed:"Vynechaná období",facts:"Příspěvky faktů",unit:"Jednotka",mode:"Způsob výpočtu",parameter:"Parametr faktu",baseline:"Počáteční hodnota",targetValue:"Cílová hodnota",criticalValue:"Kritická hodnota",direction:"Žádoucí směr",refresh:"Období aktualizace, dny",inactivity:"Změna za vynechané období",trendWindow:"Okno trendu, dny",rules:"Koeficienty efektu",ruleHelp:"Koeficienty mění jen analytiku, nikdy fakta.",search:"Najít zdrojový list",sourceParameter:"Zdrojový parametr",coefficient:"Koeficient",add:"Přidat",remove:"Odstranit",empty:"Žádné aktivní koeficienty.",notConfigured:"Profil není nastaven."},
};

const INITIAL:Form={unit:"unit",mode:"effect_rules",parameter:"process_count",baseline:"0",target:"",critical:"",direction:"increase",refreshDays:"",inactivityDelta:"0",trendDays:"30"};
function val(v:number|null|undefined){return v===null||v===undefined?"":String(v);} function show(v:number|null|undefined){return v===null||v===undefined||!Number.isFinite(v)?"—":new Intl.NumberFormat(undefined,{maximumFractionDigits:3}).format(v);} function days(v:number|null|undefined){return v===null||v===undefined||!Number.isFinite(v)?"—":String(Math.max(0,Math.ceil(v)));}
function uid(){if(typeof crypto!=="undefined"&&"randomUUID" in crypto)return crypto.randomUUID();throw new Error("UUID unavailable");}

export function ValueObjectAnalyticsProfileManager({valueObjectId,locale}:{readonly valueObjectId:string;readonly locale:LocaleCode}){
  const t=TEXT[locale]; const [open,setOpen]=useState(false); const [bundle,setBundle]=useState<Bundle|null>(null); const [form,setForm]=useState<Form>(INITIAL); const [busy,setBusy]=useState(false); const [error,setError]=useState("");
  const [query,setQuery]=useState(""); const [results,setResults]=useState<SelectorItem[]>([]); const [source,setSource]=useState<SelectorItem|null>(null); const [sourceParameter,setSourceParameter]=useState("process_count"); const [coefficient,setCoefficient]=useState("1");
  const rules=useMemo(()=> (bundle?.rules??[]).filter(r=>r.status==="active"),[bundle?.rules]);
  function apply(next:Bundle){setBundle(next);const p=next.profile;if(p)setForm({unit:p.accumulated_unit_code,mode:p.calculation_mode,parameter:p.source_parameter_code,baseline:val(p.baseline_value),target:val(p.target_value),critical:val(p.critical_value),direction:p.desired_direction,refreshDays:val(p.refresh_period_days),inactivityDelta:val(p.inactivity_delta),trendDays:val(p.trend_window_days)});}
  async function load(){setBusy(true);setError("");try{const r=await fetch(`/api/value-objects/${encodeURIComponent(valueObjectId)}/analytics-profile`,{cache:"no-store",credentials:"same-origin"});const p=await r.json().catch(()=>null) as Bundle|null;if(!r.ok||p?.ok!==true)throw new Error(p?.error||`Analytics read failed: ${r.status}`);apply(p);}catch(e){setError(e instanceof Error?e.message:"Analytics read failed");}finally{setBusy(false);}}
  async function save(){setBusy(true);setError("");try{const r=await fetch(`/api/value-objects/${encodeURIComponent(valueObjectId)}/analytics-profile`,{method:"PUT",credentials:"same-origin",headers:{"Content-Type":"application/json"},body:JSON.stringify({accumulatedUnitCode:form.unit.trim(),calculationMode:form.mode,sourceParameterCode:form.parameter.trim().toLowerCase(),baselineValue:Number(form.baseline),targetValue:form.target.trim()?Number(form.target):null,criticalValue:form.critical.trim()?Number(form.critical):null,desiredDirection:form.direction,refreshPeriodDays:form.refreshDays.trim()?Number(form.refreshDays):null,inactivityDelta:Number(form.inactivityDelta),trendWindowDays:Number(form.trendDays)})});const p=await r.json().catch(()=>null) as Bundle|null;if(!r.ok||p?.ok!==true)throw new Error(p?.error||`Analytics save failed: ${r.status}`);apply({ok:true,...p});}catch(e){setError(e instanceof Error?e.message:"Analytics save failed");}finally{setBusy(false);}}
  async function search(){if(query.trim().length<2)return;setBusy(true);setError("");try{const q=new URLSearchParams({q:query.trim(),level:"leaf",includeGlobal:"1",limit:"30"});const r=await fetch(`/api/value-objects/selector?${q.toString()}`,{cache:"no-store",credentials:"same-origin"});const p=await r.json().catch(()=>null) as {ok?:boolean;valueObjects?:SelectorItem[];error?:string}|null;if(!r.ok||p?.ok!==true)throw new Error(p?.error||`Search failed: ${r.status}`);setResults((p.valueObjects??[]).filter(x=>x.level==="leaf"));}catch(e){setError(e instanceof Error?e.message:"Search failed");}finally{setBusy(false);}}
  async function action(body:Record<string,unknown>){const r=await fetch(`/api/value-objects/${encodeURIComponent(valueObjectId)}/analytics-profile`,{method:"POST",credentials:"same-origin",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const p=await r.json().catch(()=>null) as Bundle|null;if(!r.ok||p?.ok!==true)throw new Error(p?.error||`Write failed: ${r.status}`);apply({ok:true,...p});}
  async function add(){if(!source){setError("Choose a source leaf.");return;}setBusy(true);setError("");try{await action({action:"save_rule",clientRuleId:uid(),sourceValueObjectId:source.id,sourceParameterCode:sourceParameter.trim().toLowerCase(),coefficient:Number(coefficient)});setSource(null);setResults([]);setQuery("");}catch(e){setError(e instanceof Error?e.message:"Could not save coefficient");}finally{setBusy(false);}}
  async function remove(id:string){setBusy(true);setError("");try{await action({action:"retire_rule",ruleId:id});}catch(e){setError(e instanceof Error?e.message:"Could not remove coefficient");}finally{setBusy(false);}}
  const state=bundle?.state??null;
  return <section className="rounded-[26px] border border-[#dfe6ff] bg-white p-6 shadow-sm">
    <button type="button" className="flex w-full items-start justify-between gap-4 text-left" onClick={()=>{if(open){setOpen(false);return;}setOpen(true);void load();}}><span><span className="block text-[11px] font-bold uppercase tracking-[0.22em] text-[#3b6ef8]">Analytics</span><span className="mt-2 block text-[20px] font-bold text-[#111827]">{t.title}</span><span className="mt-2 block max-w-[900px] text-[13px] leading-6 text-[#5a5f7a]">{t.intro}</span></span><span className="rounded-full border border-[#dfe3f1] px-3 py-1 text-[12px] font-bold text-[#4a4f6a]">{open?t.close:t.open}</span></button>
    {open?<div className="mt-5 grid gap-5">{error?<div className="rounded-xl border border-red-200 bg-red-50 p-3 text-[13px] font-semibold text-red-800">{error}</div>:null}{busy?<div className="text-[13px] text-[#7c8099]">…</div>:null}
      {state?<div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[[t.current,`${show(state.currentValue)} ${state.accumulatedUnitCode}`],[t.trend,`${state.trendDirection} (${show(state.trendDelta)})`],[t.rate,show(state.ratePerDay)],[t.target,show(state.targetValue)],[t.critical,show(state.criticalValue)],[t.daysTarget,days(state.daysToTarget)],[t.daysCritical,days(state.daysToCritical)],[t.missed,String(state.missedRefreshPeriods)],[t.facts,String(state.factContributions)]].map(([l,v])=><div key={l} className="rounded-2xl border border-[#edf0f7] bg-[#fafbff] p-4"><div className="text-[10px] font-bold uppercase tracking-[0.12em] text-[#7c8099]">{l}</div><div className="mt-1 text-[16px] font-bold text-[#111827]">{v}</div></div>)}</div>:bundle?<div className="rounded-xl border border-dashed border-[#c9d5ff] bg-[#f7f9ff] p-4 text-[13px] text-[#5a5f7a]">{t.notConfigured}</div>:null}
      <div className="grid gap-3 md:grid-cols-2 lg:grid-cols-3">{[[t.unit,"unit","text"],[t.parameter,"parameter","text"],[t.baseline,"baseline","number"],[t.targetValue,"target","number"],[t.criticalValue,"critical","number"],[t.refresh,"refreshDays","number"],[t.inactivity,"inactivityDelta","number"],[t.trendWindow,"trendDays","number"]].map(([label,key,type])=><label key={key} className="text-[12px] font-bold text-[#343854]">{label}<input type={type} step={type==="number"?"any":undefined} value={form[key as keyof Form]} onChange={e=>setForm(c=>({...c,[key]:e.target.value}))} className="mt-1 w-full rounded-xl border border-[#dfe3f1] px-3 py-2 text-[13px]" /></label>)}
        <label className="text-[12px] font-bold text-[#343854]">{t.mode}<select value={form.mode} onChange={e=>setForm(c=>({...c,mode:e.target.value}))} className="mt-1 w-full rounded-xl border border-[#dfe3f1] px-3 py-2 text-[13px]"><option value="latest_value">latest_value</option><option value="sum_facts">sum_facts</option><option value="baseline_plus_facts">baseline_plus_facts</option><option value="effect_rules">effect_rules</option></select></label>
        <label className="text-[12px] font-bold text-[#343854]">{t.direction}<select value={form.direction} onChange={e=>setForm(c=>({...c,direction:e.target.value}))} className="mt-1 w-full rounded-xl border border-[#dfe3f1] px-3 py-2 text-[13px]"><option value="increase">increase</option><option value="decrease">decrease</option><option value="maintain">maintain</option></select></label>
      </div><button type="button" disabled={busy} onClick={()=>void save()} className="w-fit rounded-xl bg-[#3b6ef8] px-4 py-2 text-[13px] font-bold text-white disabled:opacity-50">{t.save}</button>
      <div className="rounded-2xl border border-violet-200 bg-violet-50/60 p-4"><h3 className="text-[15px] font-bold text-violet-950">{t.rules}</h3><p className="mt-1 text-[12px] leading-5 text-violet-800">{t.ruleHelp}</p>
        {rules.length?<div className="mt-3 grid gap-2">{rules.map(rule=><div key={rule.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-violet-200 bg-white p-3"><div className="text-[12px]"><strong>{rule.sourceValueObjectTitle}</strong> · {rule.source_parameter_code} × {rule.coefficient}</div><button type="button" disabled={busy} onClick={()=>void remove(rule.id)} className="text-[12px] font-bold text-red-700">{t.remove}</button></div>)}</div>:<p className="mt-3 text-[12px] text-slate-500">{t.empty}</p>}
        <div className="mt-4 grid gap-2 md:grid-cols-[1fr_auto]"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={t.search} className="rounded-xl border border-violet-200 bg-white px-3 py-2 text-[13px]"/><button type="button" disabled={busy||query.trim().length<2} onClick={()=>void search()} className="rounded-xl border border-violet-300 bg-white px-4 py-2 text-[12px] font-bold text-violet-800 disabled:opacity-50">{t.search}</button></div>
        {results.length?<div className="mt-2 max-h-48 overflow-auto rounded-xl border border-violet-200 bg-white p-2">{results.map(item=><button key={item.id} type="button" onClick={()=>setSource(item)} className={`block w-full rounded-lg px-3 py-2 text-left text-[12px] ${source?.id===item.id?"bg-violet-100":"hover:bg-slate-50"}`}><strong>{item.title}</strong>{item.pathText?<span className="block text-slate-500">{item.pathText}</span>:null}</button>)}</div>:null}
        <div className="mt-3 grid gap-3 md:grid-cols-2"><label className="text-[12px] font-bold">{t.sourceParameter}<input value={sourceParameter} onChange={e=>setSourceParameter(e.target.value)} className="mt-1 w-full rounded-xl border border-violet-200 bg-white px-3 py-2 text-[13px]"/></label><label className="text-[12px] font-bold">{t.coefficient}<input type="number" step="any" value={coefficient} onChange={e=>setCoefficient(e.target.value)} className="mt-1 w-full rounded-xl border border-violet-200 bg-white px-3 py-2 text-[13px]"/></label></div><button type="button" disabled={busy||!source} onClick={()=>void add()} className="mt-3 rounded-xl bg-violet-700 px-4 py-2 text-[12px] font-bold text-white disabled:opacity-50">{t.add}</button>
      </div>
    </div>:null}
  </section>;
}
