export type ActivityParameterLocale = "en" | "pl" | "ru" | "uk" | "de" | "es" | "cs";

type ParameterPresentation = { readonly title: string; readonly description: string };

const SYSTEM_PARAMETER_TITLES: Record<string, Record<ActivityParameterLocale, string>> = {
  "count": {
    en: "Count",
    pl: "Liczba",
    ru: "Количество",
    uk: "Кількість",
    de: "Anzahl",
    es: "Cantidad",
    cs: "Počet",
  },
  "duration": {
    en: "Duration",
    pl: "Czas trwania",
    ru: "Продолжительность",
    uk: "Тривалість",
    de: "Dauer",
    es: "Duración",
    cs: "Doba trvání",
  },
  "distance": {
    en: "Distance",
    pl: "Dystans",
    ru: "Расстояние",
    uk: "Відстань",
    de: "Distanz",
    es: "Distancia",
    cs: "Vzdálenost",
  },
  "step_count": {
    en: "Step count",
    pl: "Liczba kroków",
    ru: "Количество шагов",
    uk: "Кількість кроків",
    de: "Schrittzahl",
    es: "Número de pasos",
    cs: "Počet kroků",
  },
  "observation_count": {
    en: "Observation count",
    pl: "Liczba obserwacji",
    ru: "Количество наблюдений",
    uk: "Кількість спостережень",
    de: "Anzahl Beobachtungen",
    es: "Número de observaciones",
    cs: "Počet pozorování",
  },
  "repetition_count": {
    en: "Repetition count",
    pl: "Liczba powtórzeń",
    ru: "Количество повторений",
    uk: "Кількість повторень",
    de: "Wiederholungszahl",
    es: "Número de repeticiones",
    cs: "Počet opakování",
  },
  "set_count": {
    en: "Set count",
    pl: "Liczba serii",
    ru: "Количество подходов",
    uk: "Кількість підходів",
    de: "Satzanzahl",
    es: "Número de series",
    cs: "Počet sérií",
  },
  "liquid_volume": {
    en: "Liquid volume",
    pl: "Objętość płynu",
    ru: "Объём жидкости",
    uk: "Об’єм рідини",
    de: "Flüssigkeitsvolumen",
    es: "Volumen de líquido",
    cs: "Objem tekutiny",
  },
  "body_mass": {
    en: "Body mass",
    pl: "Masa ciała",
    ru: "Масса тела",
    uk: "Маса тіла",
    de: "Körpermasse",
    es: "Masa corporal",
    cs: "Tělesná hmotnost",
  },
  "object_mass": {
    en: "Object mass",
    pl: "Masa obiektu",
    ru: "Масса объекта",
    uk: "Маса об’єкта",
    de: "Objektmasse",
    es: "Masa del objeto",
    cs: "Hmotnost objektu",
  },
  "energy_amount": {
    en: "Energy amount",
    pl: "Ilość energii",
    ru: "Количество энергии",
    uk: "Кількість енергії",
    de: "Energiemenge",
    es: "Cantidad de energía",
    cs: "Množství energie",
  },
  "energy_intake": {
    en: "Energy intake",
    pl: "Spożycie energii",
    ru: "Поступление энергии",
    uk: "Надходження енергії",
    de: "Energieaufnahme",
    es: "Ingesta de energía",
    cs: "Příjem energie",
  },
  "energy_expenditure": {
    en: "Energy expenditure",
    pl: "Wydatek energetyczny",
    ru: "Расход энергии",
    uk: "Витрата енергії",
    de: "Energieverbrauch",
    es: "Gasto energético",
    cs: "Energetický výdej",
  },
  "energy_balance": {
    en: "Energy balance",
    pl: "Bilans energetyczny",
    ru: "Энергетический баланс",
    uk: "Енергетичний баланс",
    de: "Energiebilanz",
    es: "Balance energético",
    cs: "Energetická bilance",
  },
  "monetary_amount_pln": {
    en: "Monetary amount, PLN",
    pl: "Kwota pieniężna, PLN",
    ru: "Денежная сумма, PLN",
    uk: "Грошова сума, PLN",
    de: "Geldbetrag, PLN",
    es: "Importe monetario, PLN",
    cs: "Peněžní částka, PLN",
  },
  "monetary_amount_eur": {
    en: "Monetary amount, EUR",
    pl: "Kwota pieniężna, EUR",
    ru: "Денежная сумма, EUR",
    uk: "Грошова сума, EUR",
    de: "Geldbetrag, EUR",
    es: "Importe monetario, EUR",
    cs: "Peněžní částka, EUR",
  },
  "monetary_amount_usd": {
    en: "Monetary amount, USD",
    pl: "Kwota pieniężna, USD",
    ru: "Денежная сумма, USD",
    uk: "Грошова сума, USD",
    de: "Geldbetrag, USD",
    es: "Importe monetario, USD",
    cs: "Peněžní částka, USD",
  },
  "heart_rate": {
    en: "Heart rate",
    pl: "Tętno",
    ru: "Частота сердечных сокращений",
    uk: "Частота серцевих скорочень",
    de: "Herzfrequenz",
    es: "Frecuencia cardíaca",
    cs: "Srdeční frekvence",
  },
  "pain_intensity": {
    en: "Pain intensity",
    pl: "Natężenie bólu",
    ru: "Интенсивность боли",
    uk: "Інтенсивність болю",
    de: "Schmerzintensität",
    es: "Intensidad del dolor",
    cs: "Intenzita bolesti",
  },
  "state_score": {
    en: "State score",
    pl: "Ocena stanu",
    ru: "Оценка состояния",
    uk: "Оцінка стану",
    de: "Zustandsbewertung",
    es: "Valoración del estado",
    cs: "Hodnocení stavu",
  },
  "speed": {
    en: "Speed",
    pl: "Prędkość",
    ru: "Скорость",
    uk: "Швидкість",
    de: "Geschwindigkeit",
    es: "Velocidad",
    cs: "Rychlost",
  },
  "temperature": {
    en: "Temperature",
    pl: "Temperatura",
    ru: "Температура",
    uk: "Температура",
    de: "Temperatur",
    es: "Temperatura",
    cs: "Teplota",
  },
  "observed_text": {
    en: "Text observation",
    pl: "Obserwacja tekstowa",
    ru: "Текстовое наблюдение",
    uk: "Текстове спостереження",
    de: "Textbeobachtung",
    es: "Observación de texto",
    cs: "Textové pozorování",
  },
  "boolean_state": {
    en: "Yes/no state",
    pl: "Stan tak/nie",
    ru: "Состояние да/нет",
    uk: "Стан так/ні",
    de: "Ja/Nein-Zustand",
    es: "Estado sí/no",
    cs: "Stav ano/ne",
  },
  "observed_at": {
    en: "Observation time",
    pl: "Czas obserwacji",
    ru: "Время наблюдения",
    uk: "Час спостереження",
    de: "Beobachtungszeit",
    es: "Hora de observación",
    cs: "Čas pozorování",
  },
  "blood_pressure_systolic_mmhg": {
    en: "Systolic blood pressure",
    pl: "Ciśnienie skurczowe",
    ru: "Систолическое артериальное давление",
    uk: "Систолічний артеріальний тиск",
    de: "Systolischer Blutdruck",
    es: "Presión arterial sistólica",
    cs: "Systolický krevní tlak",
  },
  "blood_pressure_diastolic_mmhg": {
    en: "Diastolic blood pressure",
    pl: "Ciśnienie rozkurczowe",
    ru: "Диастолическое артериальное давление",
    uk: "Діастолічний артеріальний тиск",
    de: "Diastolischer Blutdruck",
    es: "Presión arterial diastólica",
    cs: "Diastolický krevní tlak",
  },
  "sleep_latency_minutes": {
    en: "Sleep latency",
    pl: "Czas zasypiania",
    ru: "Время засыпания",
    uk: "Час засинання",
    de: "Einschlafdauer",
    es: "Latencia del sueño",
    cs: "Doba usínání",
  },
  "food_mass_g": {
    en: "Food mass",
    pl: "Masa żywności",
    ru: "Масса пищи",
    uk: "Маса їжі",
    de: "Lebensmittelmasse",
    es: "Masa de alimentos",
    cs: "Hmotnost jídla",
  },
  "caffeine_mg": {
    en: "Caffeine",
    pl: "Kofeina",
    ru: "Кофеин",
    uk: "Кофеїн",
    de: "Koffein",
    es: "Cafeína",
    cs: "Kofein",
  },
  "alcohol_g": {
    en: "Alcohol",
    pl: "Alkohol",
    ru: "Алкоголь",
    uk: "Алкоголь",
    de: "Alkohol",
    es: "Alcohol",
    cs: "Alkohol",
  },
  "currency_code": {
    en: "Currency code",
    pl: "Kod waluty",
    ru: "Код валюты",
    uk: "Код валюти",
    de: "Währungscode",
    es: "Código de moneda",
    cs: "Kód měny",
  },
  "humidity_percent": {
    en: "Relative humidity",
    pl: "Wilgotność względna",
    ru: "Относительная влажность",
    uk: "Відносна вологість",
    de: "Relative Luftfeuchtigkeit",
    es: "Humedad relativa",
    cs: "Relativní vlhkost",
  },
  "cloudiness_percent": {
    en: "Cloudiness",
    pl: "Zachmurzenie",
    ru: "Облачность",
    uk: "Хмарність",
    de: "Bewölkung",
    es: "Nubosidad",
    cs: "Oblačnost",
  },
  "noise_level_db": {
    en: "Noise level",
    pl: "Poziom hałasu",
    ru: "Уровень шума",
    uk: "Рівень шуму",
    de: "Geräuschpegel",
    es: "Nivel de ruido",
    cs: "Hladina hluku",
  },
  "illumination_lux": {
    en: "Illuminance",
    pl: "Natężenie oświetlenia",
    ru: "Освещённость",
    uk: "Освітленість",
    de: "Beleuchtungsstärke",
    es: "Iluminancia",
    cs: "Osvětlenost",
  },
  "score_percent": {
    en: "Percentage score",
    pl: "Wynik procentowy",
    ru: "Результат в процентах",
    uk: "Результат у відсотках",
    de: "Prozentwert",
    es: "Resultado porcentual",
    cs: "Procentní výsledek",
  },
  "items_count": {
    en: "Item count",
    pl: "Liczba elementów",
    ru: "Количество элементов",
    uk: "Кількість елементів",
    de: "Anzahl Elemente",
    es: "Número de elementos",
    cs: "Počet položek",
  },
  "interruption_count": {
    en: "Interruption count",
    pl: "Liczba przerwań",
    ru: "Количество прерываний",
    uk: "Кількість переривань",
    de: "Anzahl Unterbrechungen",
    es: "Número de interrupciones",
    cs: "Počet přerušení",
  },
  "meal_label": {
    en: "Meal type",
    pl: "Typ posiłku",
    ru: "Тип приёма пищи",
    uk: "Тип прийому їжі",
    de: "Mahlzeittyp",
    es: "Tipo de comida",
    cs: "Typ jídla",
  },
};

const SYSTEM_PARAMETER_DESCRIPTIONS: Readonly<Record<string, Readonly<Record<ActivityParameterLocale, string>>>> = {
  count: {
    en: "Number of discrete units, actions, events or objects; what is being counted is defined by the linked leaf observation object.",
    pl: "Liczba dyskretnych jednostek, działań, zdarzeń lub obiektów; przedmiot zliczania określa powiązany liściowy obiekt obserwacji.",
    ru: "Число дискретных единиц, действий, событий или объектов; предмет подсчёта определяется связанным листовым объектом наблюдения.",
    uk: "Кількість дискретних одиниць, дій, подій або об’єктів; предмет підрахунку визначається пов’язаним листовим об’єктом спостереження.",
    de: "Anzahl diskreter Einheiten, Handlungen, Ereignisse oder Objekte; was gezählt wird, wird durch das verknüpfte Blatt-Beobachtungsobjekt bestimmt.",
    es: "Número de unidades discretas, acciones, eventos u objetos; lo que se cuenta lo define el objeto de observación hoja vinculado.",
    cs: "Počet diskrétních jednotek, akcí, událostí nebo objektů; co se počítá, určuje propojený listový objekt pozorování.",
  },
};

const DESCRIPTION_PREFIX: Record<ActivityParameterLocale, string> = {
  en: "Measured or recorded value",
  pl: "Wartość mierzona lub rejestrowana",
  ru: "Измеряемое или фиксируемое значение",
  uk: "Вимірюване або зафіксоване значення",
  de: "Gemessener oder erfasster Wert",
  es: "Valor medido o registrado",
  cs: "Měřená nebo zaznamenaná hodnota",
};

const UNIT_LABELS: Record<string, Partial<Record<ActivityParameterLocale, string>>> = {
  minute: { en: "min", pl: "min", ru: "мин", uk: "хв", de: "min", es: "min", cs: "min" },
  second: { en: "s", pl: "s", ru: "с", uk: "с", de: "s", es: "s", cs: "s" },
  hour: { en: "h", pl: "h", ru: "ч", uk: "год", de: "h", es: "h", cs: "h" },
  meter: { en: "m", pl: "m", ru: "м", uk: "м", de: "m", es: "m", cs: "m" },
  kilometer: { en: "km", pl: "km", ru: "км", uk: "км", de: "km", es: "km", cs: "km" },
  step: { en: "steps", pl: "kroki", ru: "шаги", uk: "кроки", de: "Schritte", es: "pasos", cs: "kroky" },
  count: { en: "count", pl: "liczba", ru: "шт.", uk: "шт.", de: "Anzahl", es: "cantidad", cs: "počet" },
  repetition: { en: "reps", pl: "powt.", ru: "повт.", uk: "повт.", de: "Wdh.", es: "rep.", cs: "opak." },
  set: { en: "sets", pl: "serie", ru: "подх.", uk: "підх.", de: "Sätze", es: "series", cs: "série" },
  milliliter: { en: "ml", pl: "ml", ru: "мл", uk: "мл", de: "ml", es: "ml", cs: "ml" },
  liter: { en: "l", pl: "l", ru: "л", uk: "л", de: "l", es: "l", cs: "l" },
  gram: { en: "g", pl: "g", ru: "г", uk: "г", de: "g", es: "g", cs: "g" },
  kilogram: { en: "kg", pl: "kg", ru: "кг", uk: "кг", de: "kg", es: "kg", cs: "kg" },
  milligram: { en: "mg", pl: "mg", ru: "мг", uk: "мг", de: "mg", es: "mg", cs: "mg" },
  kcal: { en: "kcal", pl: "kcal", ru: "ккал", uk: "ккал", de: "kcal", es: "kcal", cs: "kcal" },
  kilojoule: { en: "kJ", pl: "kJ", ru: "кДж", uk: "кДж", de: "kJ", es: "kJ", cs: "kJ" },
  pln: { en: "PLN", pl: "PLN", ru: "PLN", uk: "PLN", de: "PLN", es: "PLN", cs: "PLN" },
  eur: { en: "EUR", pl: "EUR", ru: "EUR", uk: "EUR", de: "EUR", es: "EUR", cs: "EUR" },
  usd: { en: "USD", pl: "USD", ru: "USD", uk: "USD", de: "USD", es: "USD", cs: "USD" },
  beat_per_minute: { en: "bpm", pl: "ud./min", ru: "уд./мин", uk: "уд./хв", de: "bpm", es: "lpm", cs: "tepů/min" },
  score_0_10: { en: "0–10", pl: "0–10", ru: "0–10", uk: "0–10", de: "0–10", es: "0–10", cs: "0–10" },
  kilometer_per_hour: { en: "km/h", pl: "km/h", ru: "км/ч", uk: "км/год", de: "km/h", es: "km/h", cs: "km/h" },
  meter_per_second: { en: "m/s", pl: "m/s", ru: "м/с", uk: "м/с", de: "m/s", es: "m/s", cs: "m/s" },
  celsius: { en: "°C", pl: "°C", ru: "°C", uk: "°C", de: "°C", es: "°C", cs: "°C" },
  text: { en: "text", pl: "tekst", ru: "текст", uk: "текст", de: "Text", es: "texto", cs: "text" },
  boolean: { en: "yes/no", pl: "tak/nie", ru: "да/нет", uk: "так/ні", de: "ja/nein", es: "sí/no", cs: "ano/ne" },
  timestamp: { en: "date/time", pl: "data/czas", ru: "дата/время", uk: "дата/час", de: "Datum/Zeit", es: "fecha/hora", cs: "datum/čas" },
  mmhg: { en: "mmHg", pl: "mmHg", ru: "мм рт. ст.", uk: "мм рт. ст.", de: "mmHg", es: "mmHg", cs: "mmHg" },
  percent: { en: "%", pl: "%", ru: "%", uk: "%", de: "%", es: "%", cs: "%" },
  decibel: { en: "dB", pl: "dB", ru: "дБ", uk: "дБ", de: "dB", es: "dB", cs: "dB" },
  lux: { en: "lx", pl: "lx", ru: "лк", uk: "лк", de: "lx", es: "lx", cs: "lx" },
};

export function getActivityParameterPresentation(
  parameterCode: string,
  locale: ActivityParameterLocale,
  fallbackTitle: string,
  fallbackDescription: string | null,
): ParameterPresentation {
  const titles = SYSTEM_PARAMETER_TITLES[parameterCode];

  if (!titles) {
    return {
      title: fallbackTitle,
      description: fallbackDescription ?? "",
    };
  }

  const title = titles[locale] ?? titles.en ?? fallbackTitle;
  const descriptions = SYSTEM_PARAMETER_DESCRIPTIONS[parameterCode];
  return {
    title,
    description: descriptions?.[locale] ?? descriptions?.en ?? `${DESCRIPTION_PREFIX[locale] ?? DESCRIPTION_PREFIX.en}: ${title}.`,
  };
}

export function getActivityUnitLabel(
  unitCode: string,
  locale: ActivityParameterLocale,
): string {
  const labels = UNIT_LABELS[unitCode];
  return labels?.[locale] ?? labels?.en ?? unitCode;
}
