import type { AnalyticsDashboardViewModel } from "./analytics-dashboard.types";

export const analyticsDashboardFixture = {
  period: {
    label: "Current planning week",
    startDate: "2026-06-01",
    endDate: "2026-06-07",
    timezone: "Europe/Warsaw",
  },
  sourceContext: {
    label: "Fixture-first analytics preview",
    description:
      "Static read-only preview data for the UI-11 analytics dashboard. These numbers are interface signals, not persisted facts.",
    mode: "fixture-first",
    updatedAtLabel: "Prepared for UI-11 visual implementation",
  },
  summaryCards: [
    {
      id: "balance-score",
      label: "Balance signal",
      value: "6.4",
      unit: "/ 9",
      deltaLabel: "+0.6 vs previous preview",
      trend: "up",
      tone: "primary",
      explanation:
        "Overall balance is shown as a preview signal across domains. The optimal zone is not necessarily the maximum score.",
      boundaryText:
        "This is not a productivity truth and must not be persisted as an aggregate in UI-11.",
    },
    {
      id: "weekly-progress",
      label: "Weekly progress",
      value: "72",
      unit: "%",
      deltaLabel: "+8% visible activity coverage",
      trend: "up",
      tone: "success",
      explanation:
        "Shows how much of the planned weekly attention pattern is visible in fixture data.",
      boundaryText:
        "This is a read-only preview, not a verified source-of-truth calculation.",
    },
    {
      id: "focus-debt",
      label: "Focus debt",
      value: "3",
      unit: "areas",
      deltaLabel: "Needs review",
      trend: "flat",
      tone: "warning",
      explanation:
        "Highlights domains where attention appears below the expected planning range.",
      boundaryText:
        "Focus debt is a signal for review, not an automatic instruction.",
    },
    {
      id: "recovery-risk",
      label: "Recovery signal",
      value: "Moderate",
      deltaLabel: "Load/recovery balance needs attention",
      trend: "flat",
      tone: "warning",
      explanation:
        "Shows a soft load/recovery signal for interface testing and explanation flow.",
      boundaryText:
        "This is not a medical diagnosis, hormone claim, or treatment recommendation.",
    },
  ],
  balanceRings: [
    {
      id: "languages",
      label: "Languages",
      score: 7.4,
      maxScore: 9,
      currentLabel: "High attention",
      optimalRangeLabel: "Optimal range: 5-7",
      tone: "primary",
      status: "excess",
      explanation:
        "Language learning is strong, but the dashboard should also show possible overfocus when it crowds out other domains.",
      segments: [
        {
          id: "active-practice",
          label: "Active practice",
          value: 44,
          status: "optimal",
          tone: "primary",
        },
        {
          id: "passive-input",
          label: "Passive input",
          value: 31,
          status: "excess",
          tone: "warning",
        },
        {
          id: "review",
          label: "Review",
          value: 25,
          status: "optimal",
          tone: "success",
        },
      ],
    },
    {
      id: "work",
      label: "Work",
      score: 6.1,
      maxScore: 9,
      currentLabel: "Stable load",
      optimalRangeLabel: "Optimal range: 5-7",
      tone: "neutral",
      status: "optimal",
      explanation:
        "Work is visible and stable. UI-11 should avoid claiming that output quality was proven.",
      segments: [
        {
          id: "csp",
          label: "CSP/back-office",
          value: 55,
          status: "optimal",
          tone: "neutral",
        },
        {
          id: "opera",
          label: "Opera",
          value: 35,
          status: "optimal",
          tone: "primary",
        },
        {
          id: "admin",
          label: "Admin",
          value: 10,
          status: "low",
          tone: "muted",
        },
      ],
    },
    {
      id: "health",
      label: "Health",
      score: 5.8,
      maxScore: 9,
      currentLabel: "Maintained",
      optimalRangeLabel: "Optimal range: 5-6",
      tone: "success",
      status: "optimal",
      explanation:
        "Physical activity and recovery signals are shown only as planning feedback.",
      segments: [
        {
          id: "micro-workouts",
          label: "Micro-workouts",
          value: 45,
          status: "optimal",
          tone: "success",
        },
        {
          id: "mobility",
          label: "Mobility",
          value: 25,
          status: "low",
          tone: "warning",
        },
        {
          id: "sleep",
          label: "Sleep/recovery",
          value: 30,
          status: "optimal",
          tone: "primary",
        },
      ],
    },
    {
      id: "family",
      label: "Family",
      score: 4.2,
      maxScore: 9,
      currentLabel: "Below planned attention",
      optimalRangeLabel: "Optimal range: 5-6",
      tone: "warning",
      status: "low",
      explanation:
        "Family attention appears under the planning target in this fixture dataset.",
      segments: [
        {
          id: "childcare",
          label: "Childcare",
          value: 40,
          status: "optimal",
          tone: "success",
        },
        {
          id: "shared-time",
          label: "Shared time",
          value: 30,
          status: "low",
          tone: "warning",
        },
        {
          id: "logistics",
          label: "Family logistics",
          value: 30,
          status: "optimal",
          tone: "neutral",
        },
      ],
    },
    {
      id: "recovery",
      label: "Recovery",
      score: 3.9,
      maxScore: 9,
      currentLabel: "Recovery debt",
      optimalRangeLabel: "Optimal range: 5-6",
      tone: "warning",
      status: "low",
      explanation:
        "Recovery is intentionally visible as a weak area, but UI-11 must not turn it into a diagnosis.",
      segments: [
        {
          id: "sleep",
          label: "Sleep",
          value: 35,
          status: "low",
          tone: "warning",
        },
        {
          id: "quiet-time",
          label: "Quiet time",
          value: 25,
          status: "low",
          tone: "warning",
        },
        {
          id: "walks",
          label: "Walks",
          value: 40,
          status: "optimal",
          tone: "success",
        },
      ],
    },
    {
      id: "marketing",
      label: "Marketing",
      score: 4.6,
      maxScore: 9,
      currentLabel: "Needs activation",
      optimalRangeLabel: "Optimal range: 5-6",
      tone: "warning",
      status: "low",
      explanation:
        "Marketing and positioning work is visible as a candidate for review.",
      segments: [
        {
          id: "content",
          label: "Content",
          value: 30,
          status: "low",
          tone: "warning",
        },
        {
          id: "sales-assets",
          label: "Sales assets",
          value: 45,
          status: "optimal",
          tone: "primary",
        },
        {
          id: "outreach",
          label: "Outreach",
          value: 25,
          status: "low",
          tone: "warning",
        },
      ],
    },
    {
      id: "management",
      label: "Management",
      score: 5.3,
      maxScore: 9,
      currentLabel: "Planning visible",
      optimalRangeLabel: "Optimal range: 5-6",
      tone: "primary",
      status: "optimal",
      explanation:
        "Planning and project management are visible without claiming that business outcomes are proven.",
      segments: [
        {
          id: "planning",
          label: "Planning",
          value: 50,
          status: "optimal",
          tone: "primary",
        },
        {
          id: "systems",
          label: "Systems",
          value: 30,
          status: "optimal",
          tone: "success",
        },
        {
          id: "review",
          label: "Review",
          value: 20,
          status: "low",
          tone: "warning",
        },
      ],
    },
  ],
  weeklyProgress: [
    {
      id: "balance",
      label: "Balance",
      tone: "primary",
      points: [
        {
          day: "Mon",
          date: "2026-06-01",
          score: 5.8,
          load: 7.1,
          recovery: 4.4,
          note: "Strong work and language load.",
        },
        {
          day: "Tue",
          date: "2026-06-02",
          score: 6.2,
          load: 6.8,
          recovery: 4.7,
          note: "Better balance but still low recovery.",
        },
        {
          day: "Wed",
          date: "2026-06-03",
          score: 6.6,
          load: 6.2,
          recovery: 5.1,
          note: "More balanced planning day.",
        },
        {
          day: "Thu",
          date: "2026-06-04",
          score: 6.4,
          load: 6.9,
          recovery: 4.6,
          note: "Analytics dashboard implementation day.",
        },
        {
          day: "Fri",
          date: "2026-06-05",
          score: 6.1,
          load: 6.5,
          recovery: 4.8,
          note: "Projected fixture day.",
        },
        {
          day: "Sat",
          date: "2026-06-06",
          score: 5.9,
          load: 6.7,
          recovery: 4.9,
          note: "Projected mixed work/family day.",
        },
        {
          day: "Sun",
          date: "2026-06-07",
          score: 6.7,
          load: 5.2,
          recovery: 5.8,
          note: "Projected recovery and family correction.",
        },
      ],
    },
    {
      id: "load",
      label: "Load",
      tone: "warning",
      points: [
        {
          day: "Mon",
          date: "2026-06-01",
          score: 7.1,
          load: 7.1,
          recovery: 4.4,
          note: "High load signal.",
        },
        {
          day: "Tue",
          date: "2026-06-02",
          score: 6.8,
          load: 6.8,
          recovery: 4.7,
          note: "Load still elevated.",
        },
        {
          day: "Wed",
          date: "2026-06-03",
          score: 6.2,
          load: 6.2,
          recovery: 5.1,
          note: "Load closer to balanced.",
        },
        {
          day: "Thu",
          date: "2026-06-04",
          score: 6.9,
          load: 6.9,
          recovery: 4.6,
          note: "Implementation load visible.",
        },
        {
          day: "Fri",
          date: "2026-06-05",
          score: 6.5,
          load: 6.5,
          recovery: 4.8,
          note: "Projected load.",
        },
        {
          day: "Sat",
          date: "2026-06-06",
          score: 6.7,
          load: 6.7,
          recovery: 4.9,
          note: "Projected load.",
        },
        {
          day: "Sun",
          date: "2026-06-07",
          score: 5.2,
          load: 5.2,
          recovery: 5.8,
          note: "Projected lower load.",
        },
      ],
    },
    {
      id: "recovery",
      label: "Recovery",
      tone: "success",
      points: [
        {
          day: "Mon",
          date: "2026-06-01",
          score: 4.4,
          load: 7.1,
          recovery: 4.4,
          note: "Recovery below target.",
        },
        {
          day: "Tue",
          date: "2026-06-02",
          score: 4.7,
          load: 6.8,
          recovery: 4.7,
          note: "Small improvement.",
        },
        {
          day: "Wed",
          date: "2026-06-03",
          score: 5.1,
          load: 6.2,
          recovery: 5.1,
          note: "Recovery reaches planning zone.",
        },
        {
          day: "Thu",
          date: "2026-06-04",
          score: 4.6,
          load: 6.9,
          recovery: 4.6,
          note: "Recovery again lower than load.",
        },
        {
          day: "Fri",
          date: "2026-06-05",
          score: 4.8,
          load: 6.5,
          recovery: 4.8,
          note: "Projected slight improvement.",
        },
        {
          day: "Sat",
          date: "2026-06-06",
          score: 4.9,
          load: 6.7,
          recovery: 4.9,
          note: "Projected recovery still below target.",
        },
        {
          day: "Sun",
          date: "2026-06-07",
          score: 5.8,
          load: 5.2,
          recovery: 5.8,
          note: "Projected recovery correction.",
        },
      ],
    },
  ],
  heatmap: [
    {
      domainId: "languages",
      label: "Languages",
      cells: [
        {
          domainId: "languages",
          day: "Mon",
          score: 8,
          status: "excess",
          label: "High",
          accessibleLabel: "Languages on Monday: high attention, possible excess.",
        },
        {
          domainId: "languages",
          day: "Tue",
          score: 7,
          status: "optimal",
          label: "Good",
          accessibleLabel: "Languages on Tuesday: good attention.",
        },
        {
          domainId: "languages",
          day: "Wed",
          score: 6,
          status: "optimal",
          label: "Good",
          accessibleLabel: "Languages on Wednesday: optimal attention.",
        },
        {
          domainId: "languages",
          day: "Thu",
          score: 7,
          status: "optimal",
          label: "Good",
          accessibleLabel: "Languages on Thursday: good attention.",
        },
        {
          domainId: "languages",
          day: "Fri",
          score: 6,
          status: "optimal",
          label: "Good",
          accessibleLabel: "Languages on Friday: projected optimal attention.",
        },
        {
          domainId: "languages",
          day: "Sat",
          score: 5,
          status: "optimal",
          label: "OK",
          accessibleLabel: "Languages on Saturday: projected lower but acceptable attention.",
        },
        {
          domainId: "languages",
          day: "Sun",
          score: 4,
          status: "low",
          label: "Low",
          accessibleLabel: "Languages on Sunday: projected low attention.",
        },
      ],
    },
    {
      domainId: "work",
      label: "Work",
      cells: [
        {
          domainId: "work",
          day: "Mon",
          score: 7,
          status: "optimal",
          label: "Good",
          accessibleLabel: "Work on Monday: stable visible load.",
        },
        {
          domainId: "work",
          day: "Tue",
          score: 7,
          status: "optimal",
          label: "Good",
          accessibleLabel: "Work on Tuesday: stable visible load.",
        },
        {
          domainId: "work",
          day: "Wed",
          score: 5,
          status: "optimal",
          label: "OK",
          accessibleLabel: "Work on Wednesday: moderate load.",
        },
        {
          domainId: "work",
          day: "Thu",
          score: 7,
          status: "optimal",
          label: "Good",
          accessibleLabel: "Work on Thursday: implementation and work load visible.",
        },
        {
          domainId: "work",
          day: "Fri",
          score: 6,
          status: "optimal",
          label: "Good",
          accessibleLabel: "Work on Friday: projected stable load.",
        },
        {
          domainId: "work",
          day: "Sat",
          score: 7,
          status: "optimal",
          label: "Good",
          accessibleLabel: "Work on Saturday: projected high but acceptable load.",
        },
        {
          domainId: "work",
          day: "Sun",
          score: 3,
          status: "low",
          label: "Low",
          accessibleLabel: "Work on Sunday: projected low load.",
        },
      ],
    },
    {
      domainId: "health",
      label: "Health",
      cells: [
        {
          domainId: "health",
          day: "Mon",
          score: 5,
          status: "optimal",
          label: "OK",
          accessibleLabel: "Health on Monday: micro-activity visible.",
        },
        {
          domainId: "health",
          day: "Tue",
          score: 5,
          status: "optimal",
          label: "OK",
          accessibleLabel: "Health on Tuesday: micro-activity visible.",
        },
        {
          domainId: "health",
          day: "Wed",
          score: 6,
          status: "optimal",
          label: "Good",
          accessibleLabel: "Health on Wednesday: good activity balance.",
        },
        {
          domainId: "health",
          day: "Thu",
          score: 5,
          status: "optimal",
          label: "OK",
          accessibleLabel: "Health on Thursday: maintained activity.",
        },
        {
          domainId: "health",
          day: "Fri",
          score: 5,
          status: "optimal",
          label: "OK",
          accessibleLabel: "Health on Friday: projected maintained activity.",
        },
        {
          domainId: "health",
          day: "Sat",
          score: 4,
          status: "low",
          label: "Low",
          accessibleLabel: "Health on Saturday: projected lower mobility.",
        },
        {
          domainId: "health",
          day: "Sun",
          score: 6,
          status: "optimal",
          label: "Good",
          accessibleLabel: "Health on Sunday: projected recovery walk or mobility.",
        },
      ],
    },
    {
      domainId: "family",
      label: "Family",
      cells: [
        {
          domainId: "family",
          day: "Mon",
          score: 3,
          status: "low",
          label: "Low",
          accessibleLabel: "Family on Monday: low shared-time signal.",
        },
        {
          domainId: "family",
          day: "Tue",
          score: 4,
          status: "low",
          label: "Low",
          accessibleLabel: "Family on Tuesday: below target.",
        },
        {
          domainId: "family",
          day: "Wed",
          score: 5,
          status: "optimal",
          label: "OK",
          accessibleLabel: "Family on Wednesday: acceptable attention.",
        },
        {
          domainId: "family",
          day: "Thu",
          score: 4,
          status: "low",
          label: "Low",
          accessibleLabel: "Family on Thursday: below target.",
        },
        {
          domainId: "family",
          day: "Fri",
          score: 4,
          status: "low",
          label: "Low",
          accessibleLabel: "Family on Friday: projected below target.",
        },
        {
          domainId: "family",
          day: "Sat",
          score: 5,
          status: "optimal",
          label: "OK",
          accessibleLabel: "Family on Saturday: projected acceptable attention.",
        },
        {
          domainId: "family",
          day: "Sun",
          score: 7,
          status: "optimal",
          label: "Good",
          accessibleLabel: "Family on Sunday: projected stronger shared-time signal.",
        },
      ],
    },
    {
      domainId: "recovery",
      label: "Recovery",
      cells: [
        {
          domainId: "recovery",
          day: "Mon",
          score: 3,
          status: "low",
          label: "Low",
          accessibleLabel: "Recovery on Monday: low recovery signal.",
        },
        {
          domainId: "recovery",
          day: "Tue",
          score: 4,
          status: "low",
          label: "Low",
          accessibleLabel: "Recovery on Tuesday: below target.",
        },
        {
          domainId: "recovery",
          day: "Wed",
          score: 5,
          status: "optimal",
          label: "OK",
          accessibleLabel: "Recovery on Wednesday: near target.",
        },
        {
          domainId: "recovery",
          day: "Thu",
          score: 4,
          status: "low",
          label: "Low",
          accessibleLabel: "Recovery on Thursday: below target.",
        },
        {
          domainId: "recovery",
          day: "Fri",
          score: 4,
          status: "low",
          label: "Low",
          accessibleLabel: "Recovery on Friday: projected below target.",
        },
        {
          domainId: "recovery",
          day: "Sat",
          score: 4,
          status: "low",
          label: "Low",
          accessibleLabel: "Recovery on Saturday: projected below target.",
        },
        {
          domainId: "recovery",
          day: "Sun",
          score: 6,
          status: "optimal",
          label: "Good",
          accessibleLabel: "Recovery on Sunday: projected correction.",
        },
      ],
    },
    {
      domainId: "marketing",
      label: "Marketing",
      cells: [
        {
          domainId: "marketing",
          day: "Mon",
          score: 4,
          status: "low",
          label: "Low",
          accessibleLabel: "Marketing on Monday: low activation.",
        },
        {
          domainId: "marketing",
          day: "Tue",
          score: 4,
          status: "low",
          label: "Low",
          accessibleLabel: "Marketing on Tuesday: low activation.",
        },
        {
          domainId: "marketing",
          day: "Wed",
          score: 5,
          status: "optimal",
          label: "OK",
          accessibleLabel: "Marketing on Wednesday: acceptable planning signal.",
        },
        {
          domainId: "marketing",
          day: "Thu",
          score: 5,
          status: "optimal",
          label: "OK",
          accessibleLabel: "Marketing on Thursday: implementation planning visible.",
        },
        {
          domainId: "marketing",
          day: "Fri",
          score: 4,
          status: "low",
          label: "Low",
          accessibleLabel: "Marketing on Friday: projected low outreach.",
        },
        {
          domainId: "marketing",
          day: "Sat",
          score: 4,
          status: "low",
          label: "Low",
          accessibleLabel: "Marketing on Saturday: projected low outreach.",
        },
        {
          domainId: "marketing",
          day: "Sun",
          score: 5,
          status: "optimal",
          label: "OK",
          accessibleLabel: "Marketing on Sunday: projected review possible.",
        },
      ],
    },
    {
      domainId: "management",
      label: "Management",
      cells: [
        {
          domainId: "management",
          day: "Mon",
          score: 5,
          status: "optimal",
          label: "OK",
          accessibleLabel: "Management on Monday: planning visible.",
        },
        {
          domainId: "management",
          day: "Tue",
          score: 5,
          status: "optimal",
          label: "OK",
          accessibleLabel: "Management on Tuesday: planning visible.",
        },
        {
          domainId: "management",
          day: "Wed",
          score: 6,
          status: "optimal",
          label: "Good",
          accessibleLabel: "Management on Wednesday: good planning signal.",
        },
        {
          domainId: "management",
          day: "Thu",
          score: 6,
          status: "optimal",
          label: "Good",
          accessibleLabel: "Management on Thursday: implementation planning visible.",
        },
        {
          domainId: "management",
          day: "Fri",
          score: 5,
          status: "optimal",
          label: "OK",
          accessibleLabel: "Management on Friday: projected stable planning.",
        },
        {
          domainId: "management",
          day: "Sat",
          score: 5,
          status: "optimal",
          label: "OK",
          accessibleLabel: "Management on Saturday: projected planning visible.",
        },
        {
          domainId: "management",
          day: "Sun",
          score: 6,
          status: "optimal",
          label: "Good",
          accessibleLabel: "Management on Sunday: projected weekly review.",
        },
      ],
    },
  ],
  weakDirections: [
    {
      id: "weak-recovery",
      domainId: "recovery",
      title: "Recovery debt",
      reason:
        "Recovery signals are lower than load signals across most fixture days.",
      signalStrength: 0.82,
      confidenceLabel: "Medium confidence fixture signal",
      tone: "warning",
      relatedEvidence: [
        {
          id: "evidence-recovery-heatmap",
          kind: "fixture",
          label: "Heatmap cells",
          description: "Recovery cells are low on five of seven days.",
        },
        {
          id: "evidence-load-series",
          kind: "preview",
          label: "Load vs recovery preview",
          description: "Load values remain above recovery values in the weekly preview.",
        },
      ],
      constraints: [
        "Do not present as a diagnosis.",
        "Do not recommend treatment.",
        "Use as a candidate for review only.",
      ],
      boundaryText:
        "Weak direction is not the final Next Best Action. UI-12 handles action selection.",
    },
    {
      id: "weak-family",
      domainId: "family",
      title: "Family shared-time gap",
      reason:
        "Family attention is below the planning range on several work-heavy days.",
      signalStrength: 0.68,
      confidenceLabel: "Medium confidence fixture signal",
      tone: "warning",
      relatedEvidence: [
        {
          id: "evidence-family-heatmap",
          kind: "fixture",
          label: "Family heatmap",
          description: "Family domain has multiple low cells before the weekend.",
        },
      ],
      constraints: [
        "Keep signal explanatory.",
        "Do not convert into automatic action.",
        "Respect calendar/free-window constraints later.",
      ],
      boundaryText:
        "This is a signal for review, not a command or a final action.",
    },
    {
      id: "weak-marketing",
      domainId: "marketing",
      title: "Marketing activation gap",
      reason:
        "Marketing and outreach are present but weaker than language and work domains.",
      signalStrength: 0.61,
      confidenceLabel: "Low-to-medium confidence fixture signal",
      tone: "warning",
      relatedEvidence: [
        {
          id: "evidence-marketing-progress",
          kind: "semantic-capital",
          label: "Semantic capital preview",
          description: "Sales assets are visible, but outreach remains lower.",
        },
      ],
      constraints: [
        "No revenue claim.",
        "No financial advice.",
        "Show as planning review candidate only.",
      ],
      boundaryText:
        "UI-11 does not choose the business action; it only shows the weak direction.",
    },
  ],
  domainTabs: [
    {
      id: "languages",
      label: "Languages",
      score: 7.4,
      status: "excess",
      summary:
        "Strong language-learning attention with a possible overfocus signal.",
      relatedRoutes: [
        {
          label: "Objects",
          href: "/objects",
          description: "Review language-related value objects.",
        },
        {
          label: "Today",
          href: "/today",
          description: "Check language activity timeline.",
        },
      ],
    },
    {
      id: "work",
      label: "Work",
      score: 6.1,
      status: "optimal",
      summary:
        "Stable work visibility without claiming verified productivity.",
      relatedRoutes: [
        {
          label: "Calendar",
          href: "/calendar",
          description: "Review work windows and blocked time.",
        },
      ],
    },
    {
      id: "health",
      label: "Health",
      score: 5.8,
      status: "optimal",
      summary:
        "Health domain is maintained as a planning signal only.",
      relatedRoutes: [
        {
          label: "Today",
          href: "/today",
          description: "Review health-related activity events.",
        },
      ],
    },
    {
      id: "family",
      label: "Family",
      score: 4.2,
      status: "low",
      summary:
        "Shared-time signal is lower than target before the weekend.",
      relatedRoutes: [
        {
          label: "Calendar",
          href: "/calendar",
          description: "Find possible family windows.",
        },
      ],
    },
    {
      id: "recovery",
      label: "Recovery",
      score: 3.9,
      status: "low",
      summary:
        "Recovery is the clearest weak signal in the fixture data.",
      relatedRoutes: [
        {
          label: "Calendar",
          href: "/calendar",
          description: "Find low-load windows.",
        },
      ],
    },
    {
      id: "marketing",
      label: "Marketing",
      score: 4.6,
      status: "low",
      summary:
        "Marketing needs activation, but UI-11 must avoid revenue claims.",
      relatedRoutes: [
        {
          label: "Objects",
          href: "/objects",
          description: "Review marketing and sales assets.",
        },
      ],
    },
    {
      id: "management",
      label: "Management",
      score: 5.3,
      status: "optimal",
      summary:
        "Planning and systems work are visible in the current fixture.",
      relatedRoutes: [
        {
          label: "Workspace",
          href: "/workspace",
          description: "Return to the main workspace.",
        },
      ],
    },
  ],
  progressDebts: [
    {
      id: "debt-recovery",
      domainId: "recovery",
      title: "Recovery attention debt",
      gap: "Recovery is below the planning range on most fixture days.",
      cause:
        "Work and language attention are visible while low-load restoration windows are limited.",
      lastActivity: "Last visible recovery correction: Wednesday preview",
      suggestedReview:
        "Review recovery windows before selecting any action in UI-12.",
      tone: "warning",
      boundaryText:
        "Progress debt is a planning signal, not a health assessment.",
    },
    {
      id: "debt-family",
      domainId: "family",
      title: "Family shared-time debt",
      gap: "Shared-time attention is below the target before the weekend.",
      cause:
        "Dense work and implementation blocks reduce available family windows.",
      lastActivity: "Last visible family correction: Wednesday preview",
      suggestedReview:
        "Review available windows and constraints before suggesting actions.",
      tone: "warning",
      boundaryText:
        "No automatic action is created from this debt in UI-11.",
    },
    {
      id: "debt-marketing",
      domainId: "marketing",
      title: "Marketing activation debt",
      gap: "Outreach and content signals are lower than planning targets.",
      cause:
        "Language learning and implementation tasks appear to take priority.",
      lastActivity: "Last visible marketing planning: Thursday preview",
      suggestedReview:
        "Review marketing object state before any next-action candidate is generated.",
      tone: "warning",
      boundaryText:
        "This is not a financial forecast or sales prediction.",
    },
  ],
  warnings: [
    {
      id: "warning-load-recovery-gap",
      title: "Load is higher than recovery",
      body:
        "The fixture preview shows load signals above recovery signals across several days.",
      severity: "warning",
      evidence: [
        {
          id: "warning-evidence-weekly-load",
          kind: "preview",
          label: "Weekly preview series",
          description: "Load values remain higher than recovery values on most days.",
        },
      ],
      boundaryText:
        "This is not a medical diagnosis and must not be displayed as health truth.",
    },
    {
      id: "warning-language-overfocus",
      title: "Possible language overfocus",
      body:
        "Language learning is strong, but UI-11 should show that too much attention in one area can reduce balance elsewhere.",
      severity: "notice",
      evidence: [
        {
          id: "warning-evidence-language-ring",
          kind: "fixture",
          label: "Balance ring",
          description: "Language score is above the preferred planning range.",
        },
      ],
      boundaryText:
        "This is a balance signal, not a judgment about productivity.",
    },
    {
      id: "warning-signal-boundary",
      title: "Analytics are signals only",
      body:
        "All dashboard values in UI-11 are fixture-first read-only signals for visual implementation.",
      severity: "info",
      evidence: [
        {
          id: "warning-evidence-boundary",
          kind: "manual",
          label: "UI-11 scope lock",
          description: "No writes, no final NBA, no diagnosis, no financial truth.",
        },
      ],
      boundaryText:
        "Do not persist these analytics aggregates in UI-11.",
    },
  ],
  navigationLinks: [
    {
      label: "Workspace",
      href: "/workspace",
      description: "Return to the main operational workspace.",
    },
    {
      label: "Today",
      href: "/today",
      description: "Review timeline and activity signals.",
    },
    {
      label: "Calendar",
      href: "/calendar",
      description: "Review free windows and blocked time.",
    },
    {
      label: "Objects",
      href: "/objects",
      description: "Review value objects and object cloud.",
    },
    {
      label: "Next Best Action",
      href: "/next",
      description:
        "Future UI-12 route for action candidates after user choice.",
    },
  ],
  readOnlyBoundary: {
    title: "UI-11 read-only analytics boundary",
    items: [
      "Fixture-first preview only.",
      "No database writes.",
      "No hidden writes.",
      "No final Next Best Action selection.",
      "No action execution.",
      "No medical diagnosis or hormone truth.",
      "No financial advice or productivity truth.",
      "Weak directions are candidates and signals only.",
    ],
    nextBlockLabel: "UI-12 Next Best Action",
    nextBlockHref: "/next",
  },
} satisfies AnalyticsDashboardViewModel;
