import type {
  BuyerConfirmationFormPreview,
  CertificateSummary,
  CommercialCoreHeader,
  CommercialCoreNavigationLink,
  CommercialCoreViewModel,
  CommercialNoRightsState,
  CommercialReadOnlyBoundary,
  OfferSummary,
  OrganizationSummary,
  PointOperationPreview,
  PointsWalletSummary,
  PublicPurchaseHistoryEntry,
  PurchaseConfirmationPreview,
  SellerConfirmationRequestPreview,
} from "./commercial-core.types";

export const commercialCoreHeaderFixture: CommercialCoreHeader = {
  title: "Commercial Core",
  eyebrow: "Fixture-first commercial preview",
  description:
    "Read-only commercial UI for organizations, offers, certificates, points and external purchase confirmations.",
  activeRoute: "organizations",
  accessState: "read-only",
};

export const commercialNavigationLinksFixture: readonly CommercialCoreNavigationLink[] = [
  {
    routeKey: "organizations",
    label: "Organizations",
    href: "/organizations",
    description: "Seller and buyer organization directory preview.",
    badge: "Read-only",
    accessState: "read-only",
  },
  {
    routeKey: "offers",
    label: "Offers",
    href: "/offers",
    description: "Commercial offer cards without platform purchase flow.",
    badge: "Fixture",
    accessState: "read-only",
  },
  {
    routeKey: "certificates",
    label: "Certificates",
    href: "/certificates",
    description: "Certificate value, points and seller payout preview.",
    badge: "Future gate",
    accessState: "future-gated",
  },
  {
    routeKey: "points",
    label: "Points",
    href: "/points",
    description: "Wallet and operation history preview.",
    badge: "Preview only",
    accessState: "read-only",
  },
  {
    routeKey: "buyer-confirmations",
    label: "Buyer confirmations",
    href: "/purchase-confirmations",
    description: "External purchase confirmation request preview.",
    badge: "Submit disabled",
    accessState: "future-gated",
  },
  {
    routeKey: "seller-confirmations",
    label: "Seller queue",
    href: "/seller/purchase-confirmations",
    description: "Seller decision queue with disabled controls.",
    badge: "Decision disabled",
    accessState: "future-gated",
  },
  {
    routeKey: "public-purchases",
    label: "Public history",
    href: "/public/purchases",
    description: "Masked public purchase history preview.",
    badge: "Masked",
    accessState: "read-only",
  },
];

export const organizationsFixture: readonly OrganizationSummary[] = [
  {
    id: "org-ecopicnic-pl",
    title: "Ecopicnic Szczecin",
    legalName: "Ecopicnic Sp. z o.o.",
    role: "seller",
    countryCode: "PL",
    derivedCurrency: "PLN",
    city: "Szczecin",
    visibility: "partner-preview",
    offersCount: 3,
    certificatesCount: 2,
    purchaseConfirmationsCount: 4,
    isReadOnlyPreview: true,
  },
  {
    id: "org-valencia-catering",
    title: "Valencia Catering Hub",
    legalName: "Valencia Catering Hub SL",
    role: "seller",
    countryCode: "ES",
    derivedCurrency: "EUR",
    city: "Valencia",
    visibility: "public-directory-preview",
    offersCount: 2,
    certificatesCount: 1,
    purchaseConfirmationsCount: 2,
    isReadOnlyPreview: true,
  },
  {
    id: "org-berlin-office",
    title: "Berlin Office Supplies",
    legalName: "Berlin Office Supplies GmbH",
    role: "seller",
    countryCode: "DE",
    derivedCurrency: "EUR",
    city: "Berlin",
    visibility: "partner-preview",
    offersCount: 2,
    certificatesCount: 1,
    purchaseConfirmationsCount: 1,
    isReadOnlyPreview: true,
  },
];

export const offersFixture: readonly OfferSummary[] = [
  {
    id: "offer-eco-cups-pl",
    organizationId: "org-ecopicnic-pl",
    organizationTitle: "Ecopicnic Szczecin",
    title: "Eco cups for small events",
    description: "Disposable tableware package for cafes, schools and small events.",
    categoryLabel: "Disposable tableware",
    derivedCurrency: "PLN",
    referenceAmount: 240,
    pointsPreview: 24,
    certificateReady: true,
    accessState: "read-only",
    actionState: "preview-only",
  },
  {
    id: "offer-catering-box-es",
    organizationId: "org-valencia-catering",
    organizationTitle: "Valencia Catering Hub",
    title: "Catering packaging starter set",
    description: "External seller offer preview for restaurants and catering teams.",
    categoryLabel: "Catering supplies",
    derivedCurrency: "EUR",
    referenceAmount: 120,
    pointsPreview: 12,
    certificateReady: true,
    accessState: "read-only",
    actionState: "future-gated",
  },
  {
    id: "offer-office-de",
    organizationId: "org-berlin-office",
    organizationTitle: "Berlin Office Supplies",
    title: "Office kitchen restock",
    description: "Office kitchen consumables preview with no platform purchase flow.",
    categoryLabel: "Office supplies",
    derivedCurrency: "EUR",
    referenceAmount: 95,
    pointsPreview: 10,
    certificateReady: false,
    accessState: "read-only",
    actionState: "visible-disabled",
  },
];

export const certificatesFixture: readonly CertificateSummary[] = [
  {
    id: "cert-eco-50-pln",
    organizationId: "org-ecopicnic-pl",
    organizationTitle: "Ecopicnic Szczecin",
    title: "50 PLN certificate preview",
    faceValue: 50,
    derivedCurrency: "PLN",
    pointsRequired: 100,
    buyerDiscountPreview: 20,
    buyerMoneyPartPreview: 30,
    sellerMoneyPartPreview: 30,
    pointsBurnedPreview: 100,
    availabilityStatus: "available-preview",
    sellerPayoutNote: "Seller receives only the money part; spent points are burned.",
    actionState: "future-gated",
  },
  {
    id: "cert-valencia-25-eur",
    organizationId: "org-valencia-catering",
    organizationTitle: "Valencia Catering Hub",
    title: "25 EUR certificate preview",
    faceValue: 25,
    derivedCurrency: "EUR",
    pointsRequired: 80,
    buyerDiscountPreview: 10,
    buyerMoneyPartPreview: 15,
    sellerMoneyPartPreview: 15,
    pointsBurnedPreview: 80,
    availabilityStatus: "not-enough-points-preview",
    sellerPayoutNote: "Points reduce buyer payment but are not seller revenue.",
    actionState: "visible-disabled",
  },
];

export const pointsWalletFixture: PointsWalletSummary = {
  ownerLabel: "Preview buyer wallet",
  balancePreview: 160,
  availablePreview: 120,
  lockedPreview: 40,
  earnedAfterSellerConfirmationPreview: 36,
  burnedOnCertificatesPreview: 100,
  derivedCurrencyContext: "PLN",
  readOnlyNotice: "Points wallet is fixture-only; no points transaction is executed in UI-14.",
};

export const pointOperationsFixture: readonly PointOperationPreview[] = [
  {
    id: "points-op-earned-001",
    kind: "earned-preview",
    label: "Earned after seller confirmation preview",
    amount: 24,
    relatedOrganizationTitle: "Ecopicnic Szczecin",
    relatedConfirmationCode: "PC-2026-0001",
    createdAtLabel: "05.06.2026",
    statusTone: "success",
    readOnlyNote: "Preview row only; earning requires future seller confirmation write gate.",
  },
  {
    id: "points-op-burned-001",
    kind: "burned-preview",
    label: "Burned on certificate preview",
    amount: -100,
    relatedOrganizationTitle: "Ecopicnic Szczecin",
    relatedCertificateTitle: "50 PLN certificate preview",
    createdAtLabel: "05.06.2026",
    statusTone: "warning",
    readOnlyNote: "Spent points are removed from circulation and are not seller money.",
  },
];

export const buyerConfirmationsFixture: readonly PurchaseConfirmationPreview[] = [
  {
    id: "pc-preview-001",
    publicCode: "PC-2026-0001",
    buyerMaskedName: "A*******r P*******i",
    sellerOrganizationId: "org-ecopicnic-pl",
    sellerOrganizationTitle: "Ecopicnic Szczecin",
    externalPurchaseAmount: 240,
    derivedCurrency: "PLN",
    proofLabel: "Receipt preview attached",
    buyerComment: "External purchase made outside the platform; seller confirmation is required.",
    status: "confirmed-by-seller",
    pointsImpactPreview: 24,
    submittedAtLabel: "05.06.2026 09:15",
    reviewedAtLabel: "05.06.2026 10:40",
    actionState: "preview-only",
  },
  {
    id: "pc-preview-002",
    publicCode: "PC-2026-0002",
    buyerMaskedName: "S***a P*******a",
    sellerOrganizationId: "org-valencia-catering",
    sellerOrganizationTitle: "Valencia Catering Hub",
    externalPurchaseAmount: 120,
    derivedCurrency: "EUR",
    proofLabel: "Proof preview required",
    buyerComment: "Pending external purchase confirmation preview.",
    status: "pending-seller-review",
    pointsImpactPreview: 12,
    submittedAtLabel: "05.06.2026 11:20",
    actionState: "future-gated",
  },
  {
    id: "pc-preview-003",
    publicCode: "PC-2026-0003",
    buyerMaskedName: "M****a K*****a",
    sellerOrganizationId: "org-berlin-office",
    sellerOrganizationTitle: "Berlin Office Supplies",
    externalPurchaseAmount: 95,
    derivedCurrency: "EUR",
    proofLabel: "Receipt preview unclear",
    buyerComment: "Rejected preview can later be confirmed through a future seller gate.",
    status: "rejected-by-seller",
    pointsImpactPreview: 0,
    submittedAtLabel: "04.06.2026 16:30",
    reviewedAtLabel: "04.06.2026 18:10",
    actionState: "visible-disabled",
  },
];

export const buyerConfirmationFormFixture: BuyerConfirmationFormPreview = {
  sellerOrganizationOptions: organizationsFixture,
  selectedOrganizationId: "org-ecopicnic-pl",
  externalPurchaseAmountPreview: 240,
  derivedCurrency: "PLN",
  proofRequirementLabel: "Receipt or short purchase comment preview",
  commentPlaceholder: "Describe the completed external purchase. Submission is disabled in UI-14.",
  submitActionState: "future-gated",
  submitDisabledReason: "Purchase confirmation submission requires a future commercial write gate.",
};

export const sellerQueueFixture: readonly SellerConfirmationRequestPreview[] = [
  {
    id: "seller-pc-preview-001",
    publicCode: "PC-2026-0002",
    buyerMaskedName: "S***a P*******a",
    sellerOrganizationId: "org-valencia-catering",
    sellerOrganizationTitle: "Valencia Catering Hub",
    externalPurchaseAmount: 120,
    derivedCurrency: "EUR",
    status: "pending-seller-review",
    proofLabel: "Proof preview required",
    buyerComment: "Seller decision controls are disabled in UI-14.",
    pointsImpactPreview: 12,
    availableDecisions: ["confirm-disabled", "reject-disabled"],
    decisionDisabledReason: "Seller approve/reject actions require a future commercial write gate.",
  },
  {
    id: "seller-pc-preview-002",
    publicCode: "PC-2026-0003",
    buyerMaskedName: "M****a K*****a",
    sellerOrganizationId: "org-berlin-office",
    sellerOrganizationTitle: "Berlin Office Supplies",
    externalPurchaseAmount: 95,
    derivedCurrency: "EUR",
    status: "rejected-by-seller",
    proofLabel: "Receipt preview unclear",
    buyerComment: "Confirm-later is visible only as a disabled future capability.",
    pointsImpactPreview: 0,
    availableDecisions: ["confirm-later-disabled"],
    decisionDisabledReason: "Confirm-later after mistaken rejection is not active in UI-14.",
  },
];

export const publicHistoryFixture: readonly PublicPurchaseHistoryEntry[] = [
  {
    id: "public-purchase-001",
    buyerMaskedName: "A*******r P*******i",
    sellerOrganizationTitle: "Ecopicnic Szczecin",
    sellerCity: "Szczecin",
    externalPurchaseAmount: 240,
    derivedCurrency: "PLN",
    confirmationStatus: "confirmed-by-seller",
    confirmationDateLabel: "05.06.2026",
    publicSafetyNote: "Buyer identity is masked; company name stays open.",
  },
  {
    id: "public-purchase-002",
    buyerMaskedName: "S***a P*******a",
    sellerOrganizationTitle: "Valencia Catering Hub",
    sellerCity: "Valencia",
    externalPurchaseAmount: 120,
    derivedCurrency: "EUR",
    confirmationStatus: "pending-seller-review",
    confirmationDateLabel: "05.06.2026",
    publicSafetyNote: "Pending preview row; full buyer name is never public.",
  },
];

export const commercialReadOnlyBoundaryFixture: CommercialReadOnlyBoundary = {
  title: "Read-only commercial boundary",
  description:
    "UI-14 displays commercial data from fixtures only. Real writes require a separate future gate.",
  blockedActions: [
    "Create organization",
    "Create or edit offer",
    "Buy or use certificate",
    "Award, spend or burn points",
    "Submit buyer purchase confirmation",
    "Approve, reject or confirm-later seller request",
    "Create public purchase history item",
    "Change organization currency",
  ],
  futureGateRequired: true,
  noHiddenWritesNotice: "No DB, API, server action or client mutation is allowed in this fixture phase.",
};

export const commercialNoRightsStateFixture: CommercialNoRightsState = {
  title: "Commercial access is not active",
  description:
    "This preview state is shown when an actor has no commercial rights or organization context.",
  missingRights: [
    "No seller organization selected",
    "No buyer commercial context",
    "No future write gate approval",
  ],
  safeFallbackRoute: "organizations",
  supportHint: "Use read-only organization preview until commercial permissions are configured.",
};

export const commercialCoreFixture: CommercialCoreViewModel = {
  header: commercialCoreHeaderFixture,
  navigationLinks: commercialNavigationLinksFixture,
  organizations: organizationsFixture,
  offers: offersFixture,
  certificates: certificatesFixture,
  pointsWallet: pointsWalletFixture,
  pointOperations: pointOperationsFixture,
  buyerConfirmationForm: buyerConfirmationFormFixture,
  buyerConfirmations: buyerConfirmationsFixture,
  sellerQueue: sellerQueueFixture,
  publicHistory: publicHistoryFixture,
  readOnlyBoundary: commercialReadOnlyBoundaryFixture,
  noRightsState: commercialNoRightsStateFixture,
};

