import type { CalendarFreeWindowsViewModel } from "./calendar-free-windows.types";

export const calendarFreeWindowsFixture: CalendarFreeWindowsViewModel = {
  title: "Calendar / Free Windows",
  subtitle:
    "Read-only calendar view that shows time windows, constraints and candidate actions without writing to any external calendar.",
  activeDateLabel: "This week",
  durationBuckets: [5, 10, 20, 45],
  selectedDurationBucket: 20,
  constraints: [
    {
      id: "constraint-read-only",
      label: "Read-only first",
      description:
        "UI-10 shows availability and candidates only. It does not create, edit or delete calendar events.",
    },
    {
      id: "constraint-energy",
      label: "Energy-aware",
      description:
        "Candidate actions must respect the current energy level and attention depth of the free window.",
    },
    {
      id: "constraint-family",
      label: "Family context",
      description:
        "Family time and child-care windows are treated as protected context, not as empty work time.",
    },
    {
      id: "constraint-recovery",
      label: "Recovery needed",
      description:
        "Short recovery windows should stay available for rest, breathing, mobility or low-pressure reset.",
    },
  ],
  legend: [
    {
      id: "legend-busy-work",
      label: "Busy work",
      kind: "busy",
      domain: "work",
      description: "Existing work or appointment block.",
    },
    {
      id: "legend-free",
      label: "Free window",
      kind: "free",
      domain: "mixed",
      description: "Available time window that may fit one or more candidate actions.",
    },
    {
      id: "legend-blocked-family",
      label: "Protected family",
      kind: "blocked",
      domain: "family",
      description: "Family or child-care context. Not treated as empty productivity time.",
    },
    {
      id: "legend-learning",
      label: "Learning candidate",
      kind: "free",
      domain: "learning",
      description: "Window suitable for language learning or professional study.",
    },
    {
      id: "legend-recovery",
      label: "Recovery candidate",
      kind: "free",
      domain: "recovery",
      description: "Window suitable for rest, mobility, walk or breathing reset.",
    },
  ],
  days: [
    {
      id: "day-monday",
      isoDate: "2026-06-08",
      weekdayLabel: "Mon",
      dayLabel: "Monday",
      isToday: true,
      summary: {
        busyMinutes: 420,
        freeMinutes: 150,
        blockedMinutes: 90,
        largestFreeWindowMinutes: 45,
        fittingCandidateCount: 4,
      },
      blocks: [
        {
          id: "block-mon-work-early",
          kind: "busy",
          title: "CSP work block",
          description: "Deep work context with limited switching.",
          domain: "work",
          range: {
            start: "06:30",
            end: "11:30",
            durationMinutes: 300,
          },
          source: "fixture",
          isReadOnly: true,
        },
        {
          id: "block-mon-family",
          kind: "blocked",
          title: "Family / school logistics",
          description: "Protected family context.",
          domain: "family",
          range: {
            start: "16:30",
            end: "18:00",
            durationMinutes: 90,
          },
          source: "fixture",
          isReadOnly: true,
        },
        {
          id: "block-mon-work-late",
          kind: "busy",
          title: "Evening work wrap-up",
          description: "Administrative work and unresolved tasks.",
          domain: "admin",
          range: {
            start: "18:15",
            end: "20:15",
            durationMinutes: 120,
          },
          source: "fixture",
          isReadOnly: true,
        },
      ],
      freeWindows: [
        {
          id: "window-mon-recovery-01",
          title: "Recovery reset",
          description: "Short calm window after the first long work segment.",
          domain: "recovery",
          range: {
            start: "11:30",
            end: "11:50",
            durationMinutes: 20,
          },
          energyLevel: "low",
          attentionLevel: "shallow",
          availableBuckets: [5, 10, 20],
          constraintIds: ["constraint-recovery", "constraint-read-only"],
          suggestedCandidateIds: ["candidate-breathing-reset"],
          source: "fixture",
          isReadOnly: true,
        },
        {
          id: "window-mon-learning-01",
          title: "Language practice",
          description: "A medium window suitable for active speaking drills.",
          domain: "language",
          range: {
            start: "13:10",
            end: "13:55",
            durationMinutes: 45,
          },
          energyLevel: "medium",
          attentionLevel: "focused",
          availableBuckets: [5, 10, 20, 45],
          constraintIds: ["constraint-energy", "constraint-read-only"],
          suggestedCandidateIds: ["candidate-german-speaking", "candidate-sales-phrases"],
          source: "fixture",
          isReadOnly: true,
        },
        {
          id: "window-mon-admin-01",
          title: "Admin micro-window",
          description: "Small slot for inbox triage or schedule cleanup.",
          domain: "admin",
          range: {
            start: "20:20",
            end: "20:30",
            durationMinutes: 10,
          },
          energyLevel: "low",
          attentionLevel: "shallow",
          availableBuckets: [5, 10],
          constraintIds: ["constraint-energy", "constraint-read-only"],
          suggestedCandidateIds: ["candidate-inbox-triage"],
          source: "fixture",
          isReadOnly: true,
        },
      ],
    },
    {
      id: "day-tuesday",
      isoDate: "2026-06-09",
      weekdayLabel: "Tue",
      dayLabel: "Tuesday",
      isToday: false,
      summary: {
        busyMinutes: 520,
        freeMinutes: 105,
        blockedMinutes: 60,
        largestFreeWindowMinutes: 45,
        fittingCandidateCount: 3,
      },
      blocks: [
        {
          id: "block-tue-work",
          kind: "busy",
          title: "CSP work block",
          description: "Long work period with low tolerance for context switching.",
          domain: "work",
          range: {
            start: "06:30",
            end: "17:30",
            durationMinutes: 660,
          },
          source: "fixture",
          isReadOnly: true,
        },
        {
          id: "block-tue-opera",
          kind: "busy",
          title: "Opera rehearsal",
          description: "Fixed stage or rehearsal obligation.",
          domain: "work",
          range: {
            start: "18:00",
            end: "22:00",
            durationMinutes: 240,
          },
          source: "fixture",
          isReadOnly: true,
        },
      ],
      freeWindows: [
        {
          id: "window-tue-health-01",
          title: "Mobility break",
          description: "Short window between fixed obligations.",
          domain: "health",
          range: {
            start: "17:35",
            end: "17:55",
            durationMinutes: 20,
          },
          energyLevel: "medium",
          attentionLevel: "shallow",
          availableBuckets: [5, 10, 20],
          constraintIds: ["constraint-energy", "constraint-recovery"],
          suggestedCandidateIds: ["candidate-mobility-reset"],
          source: "fixture",
          isReadOnly: true,
        },
        {
          id: "window-tue-language-01",
          title: "Passive language input",
          description: "Low-pressure listening or phrase review after rehearsal.",
          domain: "language",
          range: {
            start: "22:15",
            end: "22:35",
            durationMinutes: 20,
          },
          energyLevel: "low",
          attentionLevel: "shallow",
          availableBuckets: [5, 10, 20],
          constraintIds: ["constraint-energy", "constraint-read-only"],
          suggestedCandidateIds: ["candidate-passive-listening"],
          source: "fixture",
          isReadOnly: true,
        },
      ],
    },
    {
      id: "day-wednesday",
      isoDate: "2026-06-10",
      weekdayLabel: "Wed",
      dayLabel: "Wednesday",
      isToday: false,
      summary: {
        busyMinutes: 360,
        freeMinutes: 240,
        blockedMinutes: 120,
        largestFreeWindowMinutes: 90,
        fittingCandidateCount: 5,
      },
      blocks: [
        {
          id: "block-wed-rehearsal-morning",
          kind: "busy",
          title: "Morning rehearsal",
          description: "Fixed opera schedule.",
          domain: "work",
          range: {
            start: "10:00",
            end: "14:00",
            durationMinutes: 240,
          },
          source: "fixture",
          isReadOnly: true,
        },
        {
          id: "block-wed-rehearsal-evening",
          kind: "busy",
          title: "Evening rehearsal",
          description: "Second fixed opera block.",
          domain: "work",
          range: {
            start: "18:00",
            end: "22:00",
            durationMinutes: 240,
          },
          source: "fixture",
          isReadOnly: true,
        },
        {
          id: "block-wed-family",
          kind: "blocked",
          title: "Family window",
          description: "Protected family context.",
          domain: "family",
          range: {
            start: "15:00",
            end: "17:00",
            durationMinutes: 120,
          },
          source: "fixture",
          isReadOnly: true,
        },
      ],
      freeWindows: [
        {
          id: "window-wed-business-01",
          title: "Business planning",
          description: "Longer window suitable for strategic notes and B2B planning.",
          domain: "business",
          range: {
            start: "07:45",
            end: "09:15",
            durationMinutes: 90,
          },
          energyLevel: "high",
          attentionLevel: "deep",
          availableBuckets: [5, 10, 20, 45],
          constraintIds: ["constraint-energy", "constraint-read-only"],
          suggestedCandidateIds: ["candidate-b2b-plan", "candidate-offer-map"],
          source: "fixture",
          isReadOnly: true,
        },
        {
          id: "window-wed-learning-01",
          title: "Focused learning",
          description: "Medium window before evening rehearsal.",
          domain: "learning",
          range: {
            start: "17:05",
            end: "17:50",
            durationMinutes: 45,
          },
          energyLevel: "medium",
          attentionLevel: "focused",
          availableBuckets: [5, 10, 20, 45],
          constraintIds: ["constraint-energy", "constraint-read-only"],
          suggestedCandidateIds: ["candidate-course-review"],
          source: "fixture",
          isReadOnly: true,
        },
      ],
    },
  ],
  suggestedCandidates: [
    {
      id: "candidate-breathing-reset",
      windowId: "window-mon-recovery-01",
      title: "Two-minute breathing reset plus short walk",
      description: "Protect recovery before the next work segment.",
      domain: "recovery",
      durationBucket: 10,
      fitState: "fits",
      state: "candidate",
      reason: "Low energy and shallow attention make recovery more useful than extra task switching.",
      constraintIds: ["constraint-recovery", "constraint-energy"],
      isReadOnly: true,
    },
    {
      id: "candidate-german-speaking",
      windowId: "window-mon-learning-01",
      title: "German speaking drill",
      description: "Ten business sentences aloud with correction notes.",
      domain: "language",
      durationBucket: 20,
      fitState: "fits",
      state: "candidate",
      reason: "The window is long enough for active recall without creating schedule pressure.",
      constraintIds: ["constraint-energy"],
      isReadOnly: true,
    },
    {
      id: "candidate-sales-phrases",
      windowId: "window-mon-learning-01",
      title: "B2B objection phrases",
      description: "Review and say negotiation phrases in several languages.",
      domain: "business",
      durationBucket: 20,
      fitState: "fits",
      state: "preview",
      reason: "Business language practice fits the selected duration bucket and current positioning.",
      constraintIds: ["constraint-energy"],
      isReadOnly: true,
    },
    {
      id: "candidate-inbox-triage",
      windowId: "window-mon-admin-01",
      title: "Inbox triage",
      description: "Sort urgent messages only, without starting deep work.",
      domain: "admin",
      durationBucket: 10,
      fitState: "tight",
      state: "candidate",
      reason: "The window is short and should not open a deep task.",
      constraintIds: ["constraint-energy"],
      isReadOnly: true,
    },
    {
      id: "candidate-mobility-reset",
      windowId: "window-tue-health-01",
      title: "Mobility reset",
      description: "Shoulders, back and hips before evening rehearsal.",
      domain: "health",
      durationBucket: 20,
      fitState: "fits",
      state: "candidate",
      reason: "The window sits between fixed obligations and supports physical readiness.",
      constraintIds: ["constraint-recovery"],
      isReadOnly: true,
    },
    {
      id: "candidate-passive-listening",
      windowId: "window-tue-language-01",
      title: "Passive listening",
      description: "Light listening session without active writing.",
      domain: "language",
      durationBucket: 20,
      fitState: "fits",
      state: "candidate",
      reason: "Low energy after rehearsal makes passive input safer than active output.",
      constraintIds: ["constraint-energy"],
      isReadOnly: true,
    },
    {
      id: "candidate-b2b-plan",
      windowId: "window-wed-business-01",
      title: "B2B partner map",
      description: "Draft the next partner segment and outreach angle.",
      domain: "business",
      durationBucket: 45,
      fitState: "fits",
      state: "candidate",
      reason: "High energy and deep attention fit planning better than small admin work.",
      constraintIds: ["constraint-energy"],
      isReadOnly: true,
    },
    {
      id: "candidate-offer-map",
      windowId: "window-wed-business-01",
      title: "Offer structure map",
      description: "Write the offer logic for partner and participant sides.",
      domain: "business",
      durationBucket: 45,
      fitState: "fits",
      state: "preview",
      reason: "The long morning slot can hold strategic work without schedule conflict.",
      constraintIds: ["constraint-energy"],
      isReadOnly: true,
    },
    {
      id: "candidate-course-review",
      windowId: "window-wed-learning-01",
      title: "Course review",
      description: "Review one professional lesson and extract five useful phrases.",
      domain: "learning",
      durationBucket: 20,
      fitState: "fits",
      state: "candidate",
      reason: "A medium window before rehearsal is enough for focused but limited study.",
      constraintIds: ["constraint-energy"],
      isReadOnly: true,
    },
  ],
  navigationLinks: [
    {
      id: "nav-workspace",
      label: "Workspace",
      href: "/workspace",
      description: "Return to the main workspace dashboard.",
    },
    {
      id: "nav-today",
      label: "Today timeline",
      href: "/today",
      description: "Review the read-only daily timeline.",
    },
    {
      id: "nav-activity-today",
      label: "Activity today",
      href: "/activity-today",
      description: "Open the activity capture and review area.",
    },
    {
      id: "nav-semantic-review",
      label: "Semantic review",
      href: "/semantic/review",
      description: "Review semantic classification candidates.",
    },
    {
      id: "nav-value-objects",
      label: "Value objects",
      href: "/value-objects",
      description: "Open value object overview.",
    },
  ],
  readOnlyBoundary: {
    title: "Read-only calendar boundary",
    description:
      "This UI block previews availability and candidate actions only. It does not connect to a live calendar and does not save changes.",
    items: [
      "No external calendar events are created.",
      "No existing calendar events are edited.",
      "No database or API mutation is executed.",
      "Suggested actions are candidates, not final Next Best Action decisions.",
    ],
  },
};
