const words={
 ru:['Добавить ИИ-канал','Каналы','Название','Что искать','География','Что исключить','Домены источников (необязательно, через запятую)','Язык результата','Проверять каждые','Объекты наблюдения','Поиск объектов','Сохранить','Закрыть','Редактировать','Тестовый сбор','Опубликовать результаты','Включить сбор','Приостановить','Архивировать','Общий','Личный','Журнал запусков','Искать публикации за последние … дней','Максимум результатов','Нет подходящих результатов','ИИ-пересказ','Источник','Последняя проверка','Работаю…','Тестовый сбор использует платный API. Фактическая стоимость модели и веб-поиска списывается из AI EUR владельца канала. Лимит: 20 запусков в сутки на аккаунт.','Войдите, чтобы создать личный канал.','Показывать в ленте','Выберите от 1 до 8 существующих объектов.','Настройки сохранены','Результаты опубликованы','Архивировать канал и убрать его публикации из ленты?','Требуется установка SQL из пакета патча.','Дата публикации не подтверждена','Нет каналов'],
 en:['Add AI channel','Channels','Name','What to search for','Location','Exclude','Source domains (optional, comma separated)','Result language','Check every','Observation objects','Search objects','Save','Close','Edit','Test collection','Publish results','Enable collection','Pause','Archive','Public','Private','Run history','Lookback days','Maximum results','No matching results','AI summary','Source','Last checked','Working…','Test collection uses a paid API. Actual model and web-search cost is debited from the channel owner’s AI EUR balance. Limit: 20 runs per account per day.','Sign in to create a personal channel.','Show in feed','Choose 1–8 existing objects.','Settings saved','Results published','Archive this channel and remove its publications from the feed?','Install the SQL supplied with the patch.','Publication date unverified','No channels'],
 uk:['Додати ШІ-канал','Канали','Назва','Що шукати','Географія','Що виключити','Домени джерел (необов’язково, через кому)','Мова результату','Перевіряти кожні','Об’єкти спостереження','Пошук об’єктів','Зберегти','Закрити','Редагувати','Тестовий збір','Опублікувати результати','Увімкнути збір','Призупинити','Архівувати','Спільний','Особистий','Журнал запусків','Шукати публікації за останні … днів','Максимум результатів','Немає відповідних результатів','ШІ-переказ','Джерело','Остання перевірка','Працюю…','Тестовий збір використовує платний API. Фактична вартість моделі та веб-пошуку списується з AI EUR власника каналу. Ліміт: 20 запусків на добу.','Увійдіть, щоб створити особистий канал.','Показувати у стрічці','Оберіть 1–8 наявних об’єктів.','Налаштування збережено','Результати опубліковано','Архівувати канал і прибрати його публікації зі стрічки?','Потрібно виконати SQL із пакета патча.','Дату публікації не підтверджено','Немає каналів'],
 pl:['Dodaj kanał AI','Kanały','Nazwa','Czego szukać','Lokalizacja','Wykluczenia','Domeny źródeł (opcjonalnie, po przecinku)','Język wyników','Sprawdzaj co','Obiekty obserwacji','Szukaj obiektów','Zapisz','Zamknij','Edytuj','Zbiór testowy','Opublikuj wyniki','Włącz zbieranie','Wstrzymaj','Archiwizuj','Publiczny','Osobisty','Historia uruchomień','Publikacje z ostatnich … dni','Maksimum wyników','Brak pasujących wyników','Podsumowanie AI','Źródło','Ostatnia kontrola','Pracuję…','Test korzysta z płatnego API. Rzeczywisty koszt modelu i wyszukiwania w sieci jest pobierany z salda AI EUR właściciela kanału. Limit: 20 uruchomień na dobę.','Zaloguj się, aby utworzyć kanał osobisty.','Pokaż w aktualnościach','Wybierz 1–8 istniejących obiektów.','Ustawienia zapisane','Wyniki opublikowane','Archiwizować kanał i usunąć jego publikacje z aktualności?','Uruchom SQL dostarczony z poprawką.','Data publikacji niepotwierdzona','Brak kanałów'],
 de:['KI-Kanal hinzufügen','Kanäle','Name','Suchauftrag','Region','Ausschließen','Quelldomains (optional, durch Kommas getrennt)','Ergebnissprache','Prüfen alle','Beobachtungsobjekte','Objekte suchen','Speichern','Schließen','Bearbeiten','Testlauf','Ergebnisse veröffentlichen','Sammlung aktivieren','Pausieren','Archivieren','Öffentlich','Persönlich','Ausführungsverlauf','Zeitraum in Tagen','Maximale Ergebnisse','Keine passenden Ergebnisse','KI-Zusammenfassung','Quelle','Zuletzt geprüft','In Arbeit…','Der Test nutzt eine kostenpflichtige API. Die tatsächlichen Modell- und Websuchkosten werden vom AI-EUR-Guthaben des Kanalinhabers abgebucht. Limit: 20 Läufe pro Tag.','Melden Sie sich für einen persönlichen Kanal an.','Im Feed anzeigen','Wählen Sie 1–8 vorhandene Objekte.','Einstellungen gespeichert','Ergebnisse veröffentlicht','Kanal archivieren und seine Beiträge aus dem Feed entfernen?','SQL aus dem Patch-Paket ausführen.','Veröffentlichungsdatum unbestätigt','Keine Kanäle'],
 es:['Añadir canal de IA','Canales','Nombre','Qué buscar','Ubicación','Excluir','Dominios de fuentes (opcional, separados por comas)','Idioma del resultado','Comprobar cada','Objetos de observación','Buscar objetos','Guardar','Cerrar','Editar','Recopilación de prueba','Publicar resultados','Activar recopilación','Pausar','Archivar','Público','Personal','Historial','Días de búsqueda','Máximo de resultados','Sin resultados pertinentes','Resumen de IA','Fuente','Última comprobación','Procesando…','La prueba usa una API de pago. El coste real del modelo y de la búsqueda web se descuenta del saldo AI EUR del propietario del canal. Límite: 20 ejecuciones al día.','Inicie sesión para crear un canal personal.','Mostrar en el feed','Seleccione 1–8 objetos existentes.','Configuración guardada','Resultados publicados','¿Archivar el canal y quitar sus publicaciones del feed?','Ejecute el SQL incluido en el paquete.','Fecha de publicación sin verificar','Sin canales'],
 cs:['Přidat AI kanál','Kanály','Název','Co hledat','Oblast','Vyloučit','Domény zdrojů (volitelné, oddělené čárkou)','Jazyk výsledků','Kontrolovat každých','Objekty pozorování','Hledat objekty','Uložit','Zavřít','Upravit','Testovací sběr','Zveřejnit výsledky','Zapnout sběr','Pozastavit','Archivovat','Veřejný','Osobní','Historie spuštění','Počet dnů hledání','Maximum výsledků','Žádné odpovídající výsledky','AI shrnutí','Zdroj','Poslední kontrola','Pracuji…','Test používá placené API. Skutečná cena modelu a webového vyhledávání se odečítá ze zůstatku AI EUR vlastníka kanálu. Limit: 20 spuštění denně.','Přihlaste se a vytvořte osobní kanál.','Zobrazit v kanálu zpráv','Vyberte 1–8 existujících objektů.','Nastavení uloženo','Výsledky zveřejněny','Archivovat kanál a odstranit jeho příspěvky z přehledu?','Spusťte SQL z balíčku opravy.','Datum publikace není ověřeno','Žádné kanály']
};
export function channelWords(locale:string){return words[locale as keyof typeof words]??words.en;}

const detailWords={
  "ru": {
    "depth": "Глубина поиска",
    "quick": "Быстрый",
    "detailed": "Подробный",
    "freshness": "Актуальность",
    "recent": "Недавние публикации",
    "current": "Действующие предложения",
    "timeZone": "Часовой пояс",
    "model": "Модель ИИ",
    "active": "Сбор включён",
    "paused": "Сбор приостановлен",
    "running": "Поиск выполняется в фоне. Результат появится здесь; после перезагрузки проверка продолжится.",
    "cancel": "Остановить поиск",
    "resume": "Продолжить проверку",
    "retry": "Проверка временно прервана. Поиск мог продолжиться; повторный сбор запускать не нужно.",
    "coverage": "Проверено при поиске",
    "validUntil": "Действует до",
    "counts": "Получено / принято",
    "cost": "Подробный поиск обычно дольше и дороже. Выдача зависит от доступных источников; максимум результатов не гарантируется.",
    "currentHint": "Для действующих предложений проверяем срок действия, даже если публикация старше указанного периода.",
    "cancelHint": "Отмена не возвращает стоимость уже выполненной работы."
  },
  "en": {
    "depth": "Search depth",
    "quick": "Quick",
    "detailed": "Detailed",
    "freshness": "Freshness",
    "recent": "Recent publications",
    "current": "Currently valid offers",
    "timeZone": "Time zone",
    "model": "AI model",
    "active": "Collection enabled",
    "paused": "Collection paused",
    "running": "Search is running in the background. Results will appear here; checking resumes after a page reload.",
    "cancel": "Stop search",
    "resume": "Resume checking",
    "retry": "Checking was interrupted. Search may still be running; do not start another collection.",
    "coverage": "Search coverage",
    "validUntil": "Valid until",
    "counts": "Received / accepted",
    "cost": "Detailed search usually takes longer and costs more. Results depend on available sources; the maximum is not guaranteed.",
    "currentHint": "Current offers are checked by their validity dates, even when published before the lookback window.",
    "cancelHint": "Cancellation does not refund work already performed."
  },
  "uk": {
    "depth": "Глибина пошуку",
    "quick": "Швидкий",
    "detailed": "Докладний",
    "freshness": "Актуальність",
    "recent": "Нещодавні публікації",
    "current": "Чинні пропозиції",
    "timeZone": "Часовий пояс",
    "model": "Модель ШІ",
    "active": "Збір увімкнено",
    "paused": "Збір призупинено",
    "running": "Пошук триває у фоні. Результат з’явиться тут; перевірка відновиться після перезавантаження.",
    "cancel": "Зупинити пошук",
    "resume": "Продовжити перевірку",
    "retry": "Перевірку перервано. Пошук може тривати; не запускайте новий збір.",
    "coverage": "Охоплення пошуку",
    "validUntil": "Діє до",
    "counts": "Отримано / прийнято",
    "cost": "Докладний пошук зазвичай довший і дорожчий. Максимальна кількість результатів не гарантується.",
    "currentHint": "Для чинних пропозицій перевіряємо строк дії, навіть якщо публікація старша за вказаний період.",
    "cancelHint": "Скасування не повертає вартість уже виконаної роботи."
  },
  "pl": {
    "depth": "Dokładność wyszukiwania",
    "quick": "Szybkie",
    "detailed": "Dokładne",
    "freshness": "Aktualność",
    "recent": "Najnowsze publikacje",
    "current": "Aktualnie ważne oferty",
    "timeZone": "Strefa czasowa",
    "model": "Model AI",
    "active": "Zbieranie włączone",
    "paused": "Zbieranie wstrzymane",
    "running": "Wyszukiwanie działa w tle. Wyniki pojawią się tutaj; sprawdzanie wznowi się po odświeżeniu strony.",
    "cancel": "Zatrzymaj wyszukiwanie",
    "resume": "Wznów sprawdzanie",
    "retry": "Sprawdzanie przerwano. Wyszukiwanie może nadal trwać; nie uruchamiaj kolejnego zbierania.",
    "coverage": "Zakres wyszukiwania",
    "validUntil": "Ważne do",
    "counts": "Otrzymano / przyjęto",
    "cost": "Dokładne wyszukiwanie zwykle trwa dłużej i kosztuje więcej. Maksymalna liczba wyników nie jest gwarantowana.",
    "currentHint": "Ważność ofert sprawdzamy niezależnie od daty publikacji, także poza wybranym okresem.",
    "cancelHint": "Anulowanie nie zwraca kosztów już wykonanej pracy."
  },
  "de": {
    "depth": "Suchtiefe",
    "quick": "Schnell",
    "detailed": "Ausführlich",
    "freshness": "Aktualität",
    "recent": "Aktuelle Veröffentlichungen",
    "current": "Noch gültige Angebote",
    "timeZone": "Zeitzone",
    "model": "KI-Modell",
    "active": "Sammlung aktiv",
    "paused": "Sammlung pausiert",
    "running": "Suche läuft im Hintergrund. Ergebnisse erscheinen hier; nach Neuladen wird die Prüfung fortgesetzt.",
    "cancel": "Suche stoppen",
    "resume": "Prüfung fortsetzen",
    "retry": "Prüfung unterbrochen. Die Suche läuft möglicherweise weiter; starten Sie keine weitere Sammlung.",
    "coverage": "Suchabdeckung",
    "validUntil": "Gültig bis",
    "counts": "Erhalten / akzeptiert",
    "cost": "Ausführliche Suche dauert meist länger und kostet mehr. Die maximale Ergebniszahl ist nicht garantiert.",
    "currentHint": "Angebote werden anhand ihrer Gültigkeit geprüft, auch bei älteren Veröffentlichungen.",
    "cancelHint": "Abbrechen erstattet bereits angefallene Kosten nicht."
  },
  "es": {
    "depth": "Profundidad de búsqueda",
    "quick": "Rápida",
    "detailed": "Detallada",
    "freshness": "Actualidad",
    "recent": "Publicaciones recientes",
    "current": "Ofertas vigentes",
    "timeZone": "Zona horaria",
    "model": "Modelo de IA",
    "active": "Recopilación activada",
    "paused": "Recopilación pausada",
    "running": "La búsqueda continúa en segundo plano. Los resultados aparecerán aquí; la comprobación se reanuda al recargar.",
    "cancel": "Detener búsqueda",
    "resume": "Reanudar comprobación",
    "retry": "Comprobación interrumpida. La búsqueda puede continuar; no inicie otra recopilación.",
    "coverage": "Cobertura de búsqueda",
    "validUntil": "Válido hasta",
    "counts": "Recibidos / aceptados",
    "cost": "La búsqueda detallada suele tardar y costar más. No se garantiza la cantidad máxima de resultados.",
    "currentHint": "Se comprueba la vigencia de las ofertas incluso si se publicaron antes del período elegido.",
    "cancelHint": "Cancelar no reembolsa el trabajo ya realizado."
  },
  "cs": {
    "depth": "Hloubka hledání",
    "quick": "Rychlé",
    "detailed": "Podrobné",
    "freshness": "Aktuálnost",
    "recent": "Nedávné publikace",
    "current": "Platné nabídky",
    "timeZone": "Časové pásmo",
    "model": "Model AI",
    "active": "Sběr zapnutý",
    "paused": "Sběr pozastavený",
    "running": "Hledání běží na pozadí. Výsledky se zobrazí zde; kontrola pokračuje po obnovení stránky.",
    "cancel": "Zastavit hledání",
    "resume": "Pokračovat v kontrole",
    "retry": "Kontrola byla přerušena. Hledání může pokračovat; nespouštějte další sběr.",
    "coverage": "Rozsah hledání",
    "validUntil": "Platí do",
    "counts": "Získáno / přijato",
    "cost": "Podrobné hledání obvykle trvá déle a stojí více. Maximální počet výsledků není zaručen.",
    "currentHint": "Platnost nabídek ověřujeme i u publikací starších než zvolený interval.",
    "cancelHint": "Zrušení nevrací cenu již provedené práce."
  }
};
export function channelDetailWords(locale:string){return detailWords[locale as keyof typeof detailWords]??detailWords.en;}
